//! Operational Credentials cluster `0x003E` (Core §11.18) — joining and leaving fabrics.
//!
//! > This cluster is used to add or remove Node Operational credentials on a Commissionee or
//! > already-configured Node, as well as manage the associated Fabrics.
//!
//! It is the cluster commissioning exists to reach. Everything before it — discovery, PASE,
//! the fail-safe, the regulatory configuration — is setup; this is where a device acquires an
//! identity it did not have.
//!
//! # The order is not a suggestion
//!
//! A commissioner must issue, inside one fail-safe period:
//!
//! 1. `AttestationRequest` — prove the device is a certified product (§6.2).
//! 2. `CertificateChainRequest` ×2 — fetch the DAC and PAI to check that proof against.
//! 3. `CSRRequest` — have the device generate an operational key it has never had before.
//! 4. `AddTrustedRootCertificate` — install the fabric's root.
//! 5. `AddNOC` — install the certificate the commissioner minted from the CSR.
//!
//! §11.18.6.8 makes each step's precondition explicit, and each one refuses rather than
//! improvises: no fail-safe is `FAILSAFE_REQUIRED`, a second `AddNOC` in one period is
//! `CONSTRAINT_ERROR`, a missing CSR is `MissingCsr`, a missing root is `InvalidNOC`. The
//! last is worth reading twice — "**AddNOC always requires that the client provides the root
//! of trust certificate within the same Fail-Safe context** as the rest of the new fabric's
//! operational credentials, **even if some other fabric already uses the exact same root**".
//! A device that reused an installed root would let an administrator graft a new fabric onto
//! a root it never presented.
//!
//! # Two secrets that never move
//!
//! The operational private key is generated by the device and leaves only as a public key in
//! a CSR; it lives in the [`KeyStore`](crate::crypto::KeyStore) as a handle. The `AttestationChallenge` is the
//! third key the session derived and "SHALL NOT be included in any of the payloads conveyed"
//! — it is what makes an `AttestationResponse` unreplayable, because a signature over it
//! proves the signer was on *this* session.
//!
//! # What this cluster does not own
//!
//! §11.18.6.8's effect on receipt reaches well past the fabric table: step 6 re-advertises
//! the node over DNS-SD, step 7 adds an Access Control entry for `CaseAdminSubject`, step 10
//! binds the accessing PASE session to the new fabric. None of those belong to a cluster, so
//! `AddNOC` reports a `FabricChange` and the device applies it — the same arrangement as
//! the fail-safe's [`Cleanup`](crate::commissioning::failsafe::Cleanup), and for the same
//! reason: the work is outside a cluster's reach, so the cluster reports it rather than
//! reaching for it.
//!
//! # Revision 2
//!
//! | Revision | Change |
//! |---|---|
//! | 1 | Initial revision |
//! | 2 | The Fabric Table Vendor ID Verification Procedure (§6.4.10) |

use core::cell::{Cell, RefCell};

use crate::attestation::{self, AttestationElements};
use crate::cert::MatterCertificate;
use crate::config::Config;
use crate::crypto::{KeyHandle, KeyStore, PublicKey, SymmetricKey};
use crate::dm::access::{Access, AccessQualities, Privilege};
use crate::dm::meta::{
    AttributeDescriptor, AttributeQualities, ClusterDescriptor, CommandDescriptor, Reporting,
};
use crate::dm::{Resolved, ResolvedCommand};
use crate::fabric::{
    Credentials, Fabric, FabricIdentity, FabricTable, OPERATIONAL_CERT_MAX,
    VENDOR_ID_VERIFICATION_TBS_MAX, VID_VERIFICATION_STATEMENT_LEN,
};
use crate::im::{
    AttributeId, ClusterHandler, ClusterId, CommandId, InteractionContext, Status, StatusIb,
};
use crate::msg::{FabricIndex, NodeId, SessionId, VendorId};
use crate::platform::Rng;
use crate::tlv::{ContainerKind, Tag, TlvReader, TlvWriter, set_once};

use super::Cluster;

/// `0x003E` (§11.18.3).
pub const ID: ClusterId = 0x003E;

/// The highest revision in §11.18.1's table.
pub const REVISION: u16 = 2;

/// The largest `NOCs` value a node with `fabrics` fabrics can produce, in octets.
///
/// A read builds one whole attribute value in a scratch buffer before the server decides
/// whether it fits a message or has to be split across several (§10.6.4.3.1) — so the scratch
/// is sized by the largest *value* a node can produce, which is not the largest *message* it
/// can send. Those are different numbers, and a value larger than a message is precisely the
/// case list chunking exists for.
///
/// This is the largest of them for most nodes: a non-fabric-filtered `NOCs` read carries every
/// fabric's NOC and ICAC, each capped at [`OPERATIONAL_CERT_MAX`] by §6.1.3, plus the
/// `NOCStruct` and array framing. Five fabrics is over four kilobytes — more than three times
/// a datagram — which a node that sized its scratch by "the biggest constant I had" discovers
/// as `ResourceExhausted` from its own cluster, with nothing on the wire to explain it.
#[must_use]
pub const fn max_nocs_len(fabrics: usize) -> usize {
    // Per entry: two certificates, their octet-string headers, the `FabricIndex` and the
    // structure's own control and end-of-container octets. Sixteen is generous for the
    // framing and keeps the arithmetic obvious.
    let per_fabric = OPERATIONAL_CERT_MAX.saturating_mul(2).saturating_add(16);
    // Plus the array's own control octet and end-of-container.
    per_fabric.saturating_mul(fabrics).saturating_add(8)
}

/// `RESP_MAX` (§11.18.4.1) — "SHALL be 900 bytes".
///
/// "chosen to accommodate the maximum size of IPv6 frames, transport headers, message layer
/// headers and integrity protection and Interaction Model protocol encoding, while
/// accounting for sufficient remaining space for signatures".
pub const RESP_MAX: usize = 900;

/// `NOCs` (§11.18.5.1) — `list[NOCStruct]`, `CN`, `RAF`, mandatory.
pub const NOCS: AttributeId = 0x0000;
/// `Fabrics` (§11.18.5.2) — `list[FabricDescriptorStruct]`, `N`, `RVF`, mandatory.
pub const FABRICS: AttributeId = 0x0001;
/// `SupportedFabrics` (§11.18.5.3) — `uint8` `5 to 254`, `F`, `RV`, mandatory.
pub const SUPPORTED_FABRICS: AttributeId = 0x0002;
/// `CommissionedFabrics` (§11.18.5.4) — `uint8`, `N`, `RV`, mandatory.
pub const COMMISSIONED_FABRICS: AttributeId = 0x0003;
/// `TrustedRootCertificates` (§11.18.5.5) — `list[octstr]`, `CN`, `RV`, mandatory.
pub const TRUSTED_ROOT_CERTIFICATES: AttributeId = 0x0004;
/// `CurrentFabricIndex` (§11.18.5.6) — `uint8`, `RV`, mandatory.
pub const CURRENT_FABRIC_INDEX: AttributeId = 0x0005;

/// `AttestationRequest` (§11.18.6.1) — access `A`.
pub const ATTESTATION_REQUEST: CommandId = 0x00;
/// `AttestationResponse` (§11.18.6.2).
pub const ATTESTATION_RESPONSE: CommandId = 0x01;
/// `CertificateChainRequest` (§11.18.6.3) — access `A`.
pub const CERTIFICATE_CHAIN_REQUEST: CommandId = 0x02;
/// `CertificateChainResponse` (§11.18.6.4).
pub const CERTIFICATE_CHAIN_RESPONSE: CommandId = 0x03;
/// `CSRRequest` (§11.18.6.5) — access `A`.
pub const CSR_REQUEST: CommandId = 0x04;
/// `CSRResponse` (§11.18.6.6).
pub const CSR_RESPONSE: CommandId = 0x05;
/// `AddNOC` (§11.18.6.8) — access `A`. Not `F`: it runs over PASE, before a fabric exists.
pub const ADD_NOC: CommandId = 0x06;
/// `UpdateNOC` (§11.18.6.9) — access `AF`, and CASE only.
pub const UPDATE_NOC: CommandId = 0x07;
/// `NOCResponse` (§11.18.6.10).
pub const NOC_RESPONSE: CommandId = 0x08;
/// `UpdateFabricLabel` (§11.18.6.11) — access `AF`.
pub const UPDATE_FABRIC_LABEL: CommandId = 0x09;
/// `RemoveFabric` (§11.18.6.12) — access `A`: an administrator may remove *another* fabric.
pub const REMOVE_FABRIC: CommandId = 0x0A;
/// `AddTrustedRootCertificate` (§11.18.6.13) — access `A`, no response command.
pub const ADD_TRUSTED_ROOT_CERTIFICATE: CommandId = 0x0B;
/// `SetVIDVerificationStatement` (§11.18.6.14) — access `AF`, no response command.
pub const SET_VID_VERIFICATION_STATEMENT: CommandId = 0x0C;
/// `SignVIDVerificationRequest` (§11.18.6.15) — access `A`.
pub const SIGN_VID_VERIFICATION_REQUEST: CommandId = 0x0D;
/// `SignVIDVerificationResponse` (§11.18.6.16).
pub const SIGN_VID_VERIFICATION_RESPONSE: CommandId = 0x0E;

/// `CertificateChainTypeEnum` (§11.18.4.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CertificateChainType {
    /// `1` — "Request the DER-encoded DAC certificate".
    Dac = 1,
    /// `2` — "Request the DER-encoded PAI certificate".
    Pai = 2,
}

impl CertificateChainType {
    /// Decodes a wire value. §11.18.6.3: "If the CertificateType is not a valid value per
    /// CertificateChainTypeEnum then the command SHALL fail with a Status Code of
    /// INVALID_COMMAND" — note the *status*, not a response command, which is why this
    /// returns `None` rather than a third variant. Zero is not a value: the enumeration
    /// starts at one.
    #[must_use]
    pub const fn from_value(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Dac),
            2 => Some(Self::Pai),
            _ => None,
        }
    }
}

/// `NodeOperationalCertStatusEnum` (§11.18.4.3).
///
/// Values 7 and 8 are absent from the specification's table, so they are absent here: a gap
/// in an enumeration is information, and filling it in would invent a status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
#[non_exhaustive]
pub enum NocStatus {
    /// `0` — OK, no error.
    Ok = 0,
    /// `1` — "Public Key in the NOC does not match the public key in the NOCSR".
    InvalidPublicKey = 1,
    /// `2` — "The Node Operational ID in the NOC is not formatted correctly."
    InvalidNodeOpId = 2,
    /// `3` — "Any other validation error in NOC chain".
    InvalidNoc = 3,
    /// `4` — "No record of prior CSR for which this NOC could match".
    MissingCsr = 4,
    /// `5` — "NOCs table full, cannot add another one".
    TableFull = 5,
    /// `6` — "Invalid CaseAdminSubject field for an AddNOC command."
    InvalidAdminSubject = 6,
    /// `9` — "Trying to AddNOC instead of UpdateNOC against an existing Fabric."
    FabricConflict = 9,
    /// `10` — "Label already exists on another Fabric."
    LabelConflict = 10,
    /// `11` — "FabricIndex argument is invalid."
    InvalidFabricIndex = 11,
}

impl NocStatus {
    /// The value the enum encodes as.
    #[must_use]
    pub const fn value(self) -> u8 {
        self as u8
    }

    /// Whether this is [`NocStatus::Ok`].
    #[must_use]
    pub const fn is_ok(self) -> bool {
        matches!(self, Self::Ok)
    }
}

/// The device's attestation material — what §6.2's chain and §6.3's declaration are, for
/// this product.
///
/// Borrowed `&'static` in practice: the DAC and PAI are DER in flash, put there at
/// manufacture, and the Certification Declaration is the CMS blob the CSA signed.
#[derive(Debug, Clone, Copy)]
pub struct DeviceAttestation<'a> {
    /// The Device Attestation Certificate, DER-encoded (§6.2.2).
    pub dac: &'a [u8],
    /// The Product Attestation Intermediate, DER-encoded.
    pub pai: &'a [u8],
    /// The Certification Declaration — a CMS `SignedData`, DER-encoded (§6.3).
    pub certification_declaration: &'a [u8],
    /// A handle to the Device Attestation private key. Never the key.
    pub dac_key: KeyHandle,
    /// `firmware_information` (§6.3.2), if the product publishes one.
    pub firmware_information: Option<&'a [u8]>,
}

/// What an `AddNOC`, `UpdateNOC` or `RemoveFabric` left for the device to do.
///
/// Every variant is work outside a cluster's reach: the session table, the access-control
/// list, the DNS-SD advertisement. Reporting it keeps §11.18.6.8's eleven-step "Effect on
/// Receipt" checkable against the specification rather than scattered.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FabricChange {
    /// `AddNOC` succeeded (§11.18.6.8).
    Added {
        /// The index allocated for the new fabric.
        index: FabricIndex,
        /// Step 7: add an Access Control entry `{Privilege: Administer, AuthMode: CASE,
        /// Subjects: [this], Targets: []}` scoped to `index`.
        ///
        /// [`Acl::add_admin_for_fabric`](crate::acl::Acl::add_admin_for_fabric) builds exactly
        /// that entry — **do not skip it, and do not hand-build it**. §11.18.6.8: "Unless such
        /// an Access Control Entry is added atomically as described here, there would be no
        /// way for the caller on its given Fabric to eventually add another Access Control
        /// Entry for CASE authentication mode." The failure is silent and total: the fabric is
        /// joined, the node advertises itself, and the instant the PASE session closes nobody
        /// can administer it ever again.
        case_admin_subject: u64,
        /// Step 10a: whether the command arrived over PASE, in which case the session must be
        /// "augment … with the FabricIndex generated above, such that subsequent
        /// interactions have the proper accessing fabric".
        bind_pase_session: bool,
    },
    /// `UpdateNOC` succeeded (§11.18.6.9): re-advertise, and revoke everything tied to the
    /// previous operational identity — "except for the ongoing CASE session context, which
    /// SHALL temporarily remain valid until the NOCResponse has been successfully delivered".
    Updated {
        /// The fabric whose identity changed.
        index: FabricIndex,
    },
    /// `RemoveFabric` succeeded (§11.18.6.12).
    Removed {
        /// The fabric removed.
        index: FabricIndex,
        /// Whether it was the last one: "the device SHALL delete all Matter related data on
        /// the node which was created since it was commissioned" — a factory reset in all but
        /// name.
        was_last: bool,
        /// Whether it was the accessing fabric, in which case the session carrying this very
        /// response is among the things to be torn down.
        was_accessing: bool,
    },
}

/// A key pair generated by `CSRRequest` and not yet used by a NOC command (§11.18.6.5).
#[derive(Debug, Clone, Copy)]
struct PendingCsr {
    /// The session it was generated on. §11.18.6.7 scopes the record to a session, so one
    /// administrator's CSR cannot be consumed by another's `AddNOC`.
    session: Option<SessionId>,
    key: KeyHandle,
    public: PublicKey,
    /// `IsForUpdateNOC`: which of the two commands this key may be used by. Mixing them is
    /// `CONSTRAINT_ERROR` in both directions (§11.18.6.8, §11.18.6.9).
    for_update: bool,
}

const fn fixed(id: AttributeId) -> AttributeDescriptor {
    AttributeDescriptor::read_only(id).with_qualities(AttributeQualities::FIXED)
}

/// §11.18.5's attribute table.
///
/// `NOCs` is `RAF` — Administer to read, and fabric-scoped; `Fabrics` is `RVF` — View, and
/// fabric-scoped. The difference is deliberate: a fabric's *existence* and label are public
/// to anyone with View, and its certificates are not.
const ATTRIBUTES: &[AttributeDescriptor] = &[
    // `CN`: changes are omitted from reports as well as persisted. §11.18.5.1's contents
    // change only through `AddNOC`, `UpdateNOC` and `RemoveFabric` — each of which the client
    // that cares has just performed — so there is nothing a subscription would tell it.
    AttributeDescriptor::read_only(NOCS)
        .with_access(
            Access::read_only(Privilege::Administer).with_qualities(AccessQualities::FABRIC_SCOPED),
        )
        .with_qualities(AttributeQualities::NON_VOLATILE)
        .with_reporting(Reporting::ChangesOmitted),
    AttributeDescriptor::read_only(FABRICS)
        .with_access(
            Access::read_only(Privilege::View).with_qualities(AccessQualities::FABRIC_SCOPED),
        )
        .with_qualities(AttributeQualities::NON_VOLATILE),
    fixed(SUPPORTED_FABRICS),
    AttributeDescriptor::read_only(COMMISSIONED_FABRICS)
        .with_qualities(AttributeQualities::NON_VOLATILE),
    AttributeDescriptor::read_only(TRUSTED_ROOT_CERTIFICATES)
        .with_qualities(AttributeQualities::NON_VOLATILE)
        .with_reporting(Reporting::ChangesOmitted),
    AttributeDescriptor::read_only(CURRENT_FABRIC_INDEX),
];

/// §11.18.6's command table.
///
/// All are Administer. `UpdateNOC`, `UpdateFabricLabel` and `SetVIDVerificationStatement` add
/// `F`, so §8.8.2.3 step b.v refuses them over a session with no accessing fabric. `AddNOC`
/// and `RemoveFabric` deliberately do not: the first runs over PASE before any fabric exists,
/// and the second may target a fabric other than the caller's.
const COMMANDS: &[CommandDescriptor] = &[
    CommandDescriptor::new(ATTESTATION_REQUEST)
        .with_access(Access::invoke(Privilege::Administer))
        .with_response(ATTESTATION_RESPONSE),
    CommandDescriptor::new(CERTIFICATE_CHAIN_REQUEST)
        .with_access(Access::invoke(Privilege::Administer))
        .with_response(CERTIFICATE_CHAIN_RESPONSE),
    CommandDescriptor::new(CSR_REQUEST)
        .with_access(Access::invoke(Privilege::Administer))
        .with_response(CSR_RESPONSE),
    CommandDescriptor::new(ADD_NOC)
        .with_access(Access::invoke(Privilege::Administer))
        .with_response(NOC_RESPONSE),
    CommandDescriptor::new(UPDATE_NOC)
        .with_access(
            Access::invoke(Privilege::Administer).with_qualities(AccessQualities::FABRIC_SCOPED),
        )
        .with_response(NOC_RESPONSE),
    CommandDescriptor::new(UPDATE_FABRIC_LABEL)
        .with_access(
            Access::invoke(Privilege::Administer).with_qualities(AccessQualities::FABRIC_SCOPED),
        )
        .with_response(NOC_RESPONSE),
    CommandDescriptor::new(REMOVE_FABRIC)
        .with_access(Access::invoke(Privilege::Administer))
        .with_response(NOC_RESPONSE),
    CommandDescriptor::new(ADD_TRUSTED_ROOT_CERTIFICATE)
        .with_access(Access::invoke(Privilege::Administer)),
    CommandDescriptor::new(SET_VID_VERIFICATION_STATEMENT).with_access(
        Access::invoke(Privilege::Administer).with_qualities(AccessQualities::FABRIC_SCOPED),
    ),
    CommandDescriptor::new(SIGN_VID_VERIFICATION_REQUEST)
        .with_access(Access::invoke(Privilege::Administer))
        .with_response(SIGN_VID_VERIFICATION_RESPONSE),
];

/// The cluster descriptor.
#[must_use]
pub const fn cluster() -> ClusterDescriptor<'static> {
    ClusterDescriptor {
        id: ID,
        revision: REVISION,
        feature_map: 0,
        attributes: ATTRIBUTES,
        accepted_commands: COMMANDS,
        generated_commands: &[],
        events: &[],
    }
}

/// The Operational Credentials cluster.
///
/// Holds nothing itself: the fabric table, the key store and the fail-safe are all node state
/// this cluster manipulates on the wire's behalf. That is what makes it shareable with CASE
/// (which needs the same fabric table) and with General Commissioning (which arms the same
/// fail-safe).
pub struct OperationalCredentials<'a, C: Config, K: KeyStore, R: Rng, const N: usize> {
    /// The fabric table — the `Fabrics`, `NOCs` and `TrustedRootCertificates` attributes.
    pub fabrics: &'a RefCell<FabricTable<C, N>>,
    /// Key custody. `CSRRequest` generates into it and `RemoveFabric` destroys from it.
    pub keys: &'a RefCell<K>,
    /// The node's one source of entropy, for `CSRRequest`'s key generation.
    ///
    /// A trait rather than raw bytes, because this is driven by the interaction model rather
    /// than called directly — and it is still a *parameter*, so a test installs a
    /// deterministic generator and gets a reproducible key.
    pub rng: &'a RefCell<R>,
    /// The fail-safe every credential-changing command runs inside (§11.10.7.2).
    pub fail_safe: &'a RefCell<crate::commissioning::failsafe::FailSafe>,
    /// This product's attestation material.
    pub attestation: DeviceAttestation<'a>,
    /// The root certificate installed by `AddTrustedRootCertificate` in the current fail-safe
    /// period, awaiting the `AddNOC` that will adopt it.
    pending_root: RefCell<Option<heapless::Vec<u8, OPERATIONAL_CERT_MAX>>>,
    /// The key pair generated by `CSRRequest` in this session, awaiting a NOC command.
    pending_csr: Cell<Option<PendingCsr>>,
    /// What the last credential-changing command left for the device.
    change: Cell<Option<FabricChange>>,
}

impl<'a, C: Config, K: KeyStore, R: Rng, const N: usize> OperationalCredentials<'a, C, K, R, N> {
    /// The cluster over a device's fabric table, key store and fail-safe.
    #[must_use]
    pub fn new(
        fabrics: &'a RefCell<FabricTable<C, N>>,
        keys: &'a RefCell<K>,
        rng: &'a RefCell<R>,
        fail_safe: &'a RefCell<crate::commissioning::failsafe::FailSafe>,
        attestation: DeviceAttestation<'a>,
    ) -> Self {
        Self {
            fabrics,
            keys,
            rng,
            fail_safe,
            attestation,
            pending_root: RefCell::new(None),
            pending_csr: Cell::new(None),
            change: Cell::new(None),
        }
    }

    /// Takes the work the last credential-changing command left behind.
    ///
    /// A device calls this after every invoke against this cluster. Forgetting to means a
    /// fabric is joined with no administrator able to reach it (§11.18.6.8 step 7), or a
    /// removed fabric's sessions stay open.
    #[must_use]
    pub fn take_change(&self) -> Option<FabricChange> {
        self.change.take()
    }

    /// Discards any fail-safe-scoped state, destroying the operational key a `CSRRequest`
    /// generated and nothing used.
    ///
    /// Call this when the fail-safe expires — it is §11.10.7.2.2 step 8, "the new operational
    /// key pair temporarily generated for the purposes of NOC addition or update … SHALL be
    /// removed as it is no longer needed" — and it is idempotent.
    pub fn discard_pending(&self) {
        *self.pending_root.borrow_mut() = None;
        if let Some(pending) = self.pending_csr.take() {
            let _ = self.keys.borrow_mut().remove(pending.key);
        }
    }

    /// Drops fail-safe-scoped state that belongs to a context which has since ended.
    ///
    /// The fail-safe's own [`Progress`](crate::commissioning::failsafe::Progress) is reset
    /// when a new context is armed, so a `csr_requested` that is no longer set means this
    /// cluster's pending key belongs to a period that is over. Checking it here is what keeps
    /// a stale key from being adopted by the *next* commissioner's `AddNOC`.
    fn reap(&self, now: crate::platform::Instant) {
        let progress = self
            .fail_safe
            .borrow()
            .armed(now)
            .map(|armed| armed.progress);
        let Some(progress) = progress else {
            self.discard_pending();
            return;
        };
        if !progress.csr_requested
            && let Some(pending) = self.pending_csr.take()
        {
            let _ = self.keys.borrow_mut().remove(pending.key);
        }
        if !progress.added_trusted_root {
            *self.pending_root.borrow_mut() = None;
        }
    }

    /// The fail-safe's progress, or `FAILSAFE_REQUIRED` when nothing is armed.
    ///
    /// Every credential-changing command starts here: §11.18.6.5, §11.18.6.8, §11.18.6.9 and
    /// §11.18.6.13 all say "If this command is received without an armed fail-safe context …
    /// then this command SHALL fail with a FAILSAFE_REQUIRED status code".
    fn require_fail_safe(
        &self,
        now: crate::platform::Instant,
    ) -> Result<crate::commissioning::failsafe::Progress, Status> {
        self.fail_safe
            .borrow()
            .armed(now)
            .map(|armed| armed.progress)
            .ok_or(Status::FailsafeRequired)
    }
}

// --- The commands ------------------------------------------------------------------------------

impl<C: Config, K: KeyStore, R: Rng, const N: usize> OperationalCredentials<'_, C, K, R, N> {
    /// `AttestationRequest` (§11.18.6.1) → `AttestationResponse` (§11.18.6.2).
    ///
    /// Writes `AttestationElements [0]` and `AttestationSignature [1]` under `tag`.
    ///
    /// The signature is over `attestation_elements_message || attestation_challenge`, and the
    /// elements are signed **exactly as they will be sent** — not re-encoded. A device whose
    /// encoder differed from its signer's by one octet would produce a response no
    /// commissioner could verify, and the failure would look like a bad key.
    pub fn attestation_response(
        &self,
        nonce: &[u8; attestation::ATTESTATION_NONCE_LEN],
        timestamp: u32,
        challenge: &SymmetricKey,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let elements = AttestationElements {
            certification_declaration: self.attestation.certification_declaration,
            attestation_nonce: *nonce,
            timestamp,
            firmware_information: self.attestation.firmware_information,
        };
        let mut buf = [0u8; RESP_MAX];
        let encoded = elements.encode(&mut buf).map_err(|_| Status::Failure)?;
        let signature = attestation::sign_attestation(
            &*self.keys.borrow(),
            self.attestation.dac_key,
            encoded,
            challenge,
        )
        .map_err(|_| Status::Failure)?;

        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        full(w.start_structure(tag))?;
        full(w.octets(Tag::Context(0), encoded))?;
        full(w.octets(Tag::Context(1), signature.as_bytes()))?;
        full(w.end_container())
    }

    /// `CSRRequest` (§11.18.6.5) → `CSRResponse` (§11.18.6.6).
    ///
    /// Generates a fresh operational key pair, builds a PKCS#10 CSR over it, and signs the
    /// whole `nocsr_elements_message` with the *attestation* key. Two signatures over two
    /// different things: the CSR's own proves possession of the new operational key, and the
    /// outer one binds the request to the attested device and the live session.
    pub fn csr_response(
        &self,
        nonce: &[u8; attestation::CSR_NONCE_LEN],
        for_update: bool,
        ctx: &InteractionContext<'_>,
        random: &[u8; 32],
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let progress = self.require_fail_safe(ctx.now)?;
        // "If a prior UpdateNOC or AddNOC command was successfully executed within the
        // fail-safe timer period, then this command SHALL fail with a CONSTRAINT_ERROR."
        if progress.added_noc || progress.updated_noc {
            return Err(Status::ConstraintError);
        }
        // "If the IsForUpdateNOC field is present and set to true, but the command was
        // received over a PASE session, the command SHALL fail with an INVALID_COMMAND status
        // code, as it would never be possible to use a resulting subsequent certificate …
        // with the UpdateNOC command, which is forbidden over PASE sessions."
        if for_update && ctx.fabric_index.is_none() {
            return Err(Status::InvalidCommand);
        }
        let challenge = ctx.attestation_challenge.ok_or(Status::UnsupportedAccess)?;

        // A CSRRequest that replaces an earlier one in the same period must not leak the
        // earlier key: there is exactly one candidate operational key at a time.
        if let Some(previous) = self.pending_csr.take() {
            let _ = self.keys.borrow_mut().remove(previous.key);
        }

        let (key, public) = self
            .keys
            .borrow_mut()
            .generate(crate::crypto::KeyPurpose::Operational, random)
            .map_err(|_| Status::Failure)?;

        let mut csr_buf = [0u8; attestation::nocsr::MAX_CSR_LEN];
        let csr = crate::attestation::nocsr::build_csr(&*self.keys.borrow(), key, &mut csr_buf)
            .map_err(|_| Status::Failure)?;
        let elements = crate::attestation::nocsr::NocsrElements::new(csr, *nonce);
        let mut elements_buf = [0u8; RESP_MAX];
        let encoded = elements
            .encode(&mut elements_buf)
            .map_err(|_| Status::Failure)?;
        let signature = crate::attestation::nocsr::sign_nocsr(
            &*self.keys.borrow(),
            self.attestation.dac_key,
            encoded,
            challenge,
        )
        .map_err(|_| Status::Failure)?;

        self.pending_csr.set(Some(PendingCsr {
            session: ctx.session,
            key,
            public,
            for_update,
        }));
        self.fail_safe
            .borrow_mut()
            .record(ctx.now, |p| p.csr_requested = true)
            .map_err(|_| Status::FailsafeRequired)?;

        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        full(w.start_structure(tag))?;
        full(w.octets(Tag::Context(0), encoded))?;
        full(w.octets(Tag::Context(1), signature.as_bytes()))?;
        full(w.end_container())
    }

    /// `AddTrustedRootCertificate` (§11.18.6.13).
    ///
    /// No response command: success is a plain `SUCCESS` status. The certificate is *pending*
    /// until an `AddNOC` adopts it — §11.18.6.13 is explicit that the only way to remove a
    /// trusted root is to remove the fabric that uses it, so one installed by a fail-safe
    /// that then expired must never have been installed at all.
    pub fn add_trusted_root(
        &self,
        rcac: &[u8],
        ctx: &InteractionContext<'_>,
    ) -> Result<(), Status> {
        let progress = self.require_fail_safe(ctx.now)?;
        // "If a prior AddTrustedRootCertificate command was successfully invoked within the
        // fail-safe timer period, which would cause the new invocation to add a second root
        // certificate within a given fail-safe timer period, then this command SHALL fail
        // with a CONSTRAINT_ERROR."
        if progress.added_trusted_root {
            return Err(Status::ConstraintError);
        }
        if progress.added_noc || progress.updated_noc {
            return Err(Status::ConstraintError);
        }
        // "If the certificate … fails any validity checks, not fulfilling all the
        // requirements for a valid Matter Certificate Encoding representation, including a
        // truncated or oversize value, then this command SHALL fail with an INVALID_COMMAND."
        let parsed = MatterCertificate::decode(rcac).map_err(|_| Status::InvalidCommand)?;
        parsed
            .validate_as(crate::cert::CertType::Rcac)
            .map_err(|_| Status::InvalidCommand)?;
        // "fails any validity checks" covers the signature, and this is the only moment it can
        // be checked. §6.4.5.3 trusts a root by *provenance* rather than by its signature, so
        // nothing downstream ever verifies it: `verify_chain` checks the NOC and the ICAC
        // against this root's public key and takes the root itself as given. A root with a
        // corrupt or forged signature that is accepted here is therefore accepted for the
        // lifetime of the fabric, and every certificate under it verifies perfectly.
        //
        // A self-signature proves only that whoever produced the certificate held the key
        // inside it, which is exactly the claim a root makes about itself. Rejecting one that
        // fails costs an administrator nothing it did not already have.
        if !crate::cert::verify_self_signed(&parsed).unwrap_or(false) {
            return Err(Status::InvalidCommand);
        }
        let stored = heapless::Vec::from_slice(rcac).map_err(|_| Status::ResourceExhausted)?;

        *self.pending_root.borrow_mut() = Some(stored);
        self.fail_safe
            .borrow_mut()
            .record(ctx.now, |p| p.added_trusted_root = true)
            .map_err(|_| Status::FailsafeRequired)?;
        Ok(())
    }
}

/// `AddNOC`'s fields (§11.18.6.8).
#[derive(Debug, Clone, Copy)]
pub struct AddNocRequest<'a> {
    /// `NOCValue [0]` — the node operational certificate, Matter TLV, max 400.
    pub noc: &'a [u8],
    /// `ICACValue [1]` — the intermediate, if the chain has one.
    pub icac: Option<&'a [u8]>,
    /// `IPKValue [2]` — the epoch key for the Identity Protection Key, 16 octets.
    ///
    /// "This is needed to bootstrap a necessary configuration value for subsequent CASE to
    /// succeed", and having provided it is equivalent to a `KeySetWrite` of group key set 0.
    pub ipk: [u8; crate::crypto::SYMMETRIC_KEY_LENGTH_BYTES],
    /// `CaseAdminSubject [3]` — the subject that gets Administer over the new fabric.
    pub case_admin_subject: u64,
    /// `AdminVendorId [4]` — "the Vendor ID of the entity issuing the AddNOC command".
    pub admin_vendor_id: VendorId,
}

impl<C: Config, K: KeyStore, R: Rng, const N: usize> OperationalCredentials<'_, C, K, R, N> {
    /// `AddNOC` (§11.18.6.8) — join a fabric.
    ///
    /// Returns the `StatusCode` for the `NOCResponse`, and on success records a
    /// [`FabricChange::Added`] for [`OperationalCredentials::take_change`].
    ///
    /// Every failure here "SHALL leave all non-volatile state of the device untouched, as if
    /// the AddNOC command had never been received. **The information about the last CSR state
    /// associated with this session SHALL also be untouched** in this case, so that a valid
    /// AddNOC command MAY still be issued later that would match that CSR state." So the
    /// pending key is consumed only on the success path — a commissioner that sent a
    /// malformed NOC gets to try again without another `CSRRequest`.
    pub fn add_noc(
        &self,
        request: &AddNocRequest<'_>,
        ctx: &InteractionContext<'_>,
    ) -> Result<NocStatus, Status> {
        let progress = self.require_fail_safe(ctx.now)?;
        // These three are *status codes*, not NOCResponse error codes: the command never runs.
        if progress.added_noc || progress.updated_noc {
            return Err(Status::ConstraintError);
        }
        let Some(pending) = self.pending_csr.get() else {
            return Ok(NocStatus::MissingCsr);
        };
        if pending.session != ctx.session {
            // §11.18.6.7: the CSR record is scoped to "the same secure session". A key
            // generated for one administrator must not be adopted by another's AddNOC.
            return Ok(NocStatus::MissingCsr);
        }
        // "If the prior CSRRequest state that preceded AddNOC had the IsForUpdateNOC field
        // indicated as true, then this command SHALL fail with a CONSTRAINT_ERROR."
        if pending.for_update {
            return Err(Status::ConstraintError);
        }

        // "If no prior AddTrustedRootCertificate command was successfully executed within the
        // fail-safe timer period, then … InvalidNOC … even if some other fabric already uses
        // the exact same root of trust certificate."
        let pending_root = self.pending_root.borrow();
        let Some(rcac_bytes) = pending_root
            .as_deref()
            .filter(|_| progress.added_trusted_root)
        else {
            return Ok(NocStatus::InvalidNoc);
        };

        // §11.18.6.7's validation comes first: it is described as happening "Upon receipt",
        // before any of AddNOC's own preconditions, and it is what turns the certificate into
        // an identity the rules below can talk about.
        let identity = match validate_chain(request.noc, request.icac, rcac_bytes, &pending.public)
        {
            Ok(identity) => identity,
            Err(status) => return Ok(status),
        };

        let mut table = self.fabrics.borrow_mut();
        // "If the NOC provided in the NOCValue encodes an Operational Identifier for a <Root
        // Public Key, FabricID> pair already present on the device … FabricConflict."
        //
        // Before `TableFull`, which is the order §11.18.6.8 lists them in: an administrator
        // that should have sent `UpdateNOC` is told so even on a full device, which is the
        // more useful of the two answers.
        let compressed =
            crate::fabric::compressed_fabric_id(&identity.root_public_key, identity.fabric_id)
                .map_err(|_| Status::Failure)?;
        if table.find_by_compressed(compressed).is_some() {
            return Ok(NocStatus::FabricConflict);
        }
        // "If the device already has the CommissionedFabrics attribute equal to the
        // SupportedFabrics attribute … TableFull."
        if table.len() >= table.capacity() {
            return Ok(NocStatus::TableFull);
        }
        // "If the CaseAdminSubject field is not a valid ACL subject in the context of AuthMode
        // set to CASE, such as not being in either the Operational or CASE Authenticated Tag
        // range … InvalidAdminSubject."
        if !is_case_subject(request.case_admin_subject) {
            return Ok(NocStatus::InvalidAdminSubject);
        }

        let mut credentials = match Credentials::new(request.noc, rcac_bytes) {
            Ok(credentials) => credentials,
            Err(_) => return Ok(NocStatus::InvalidNoc),
        };
        if let Some(icac) = request.icac {
            credentials = match credentials.with_icac(icac) {
                Ok(credentials) => credentials,
                Err(_) => return Ok(NocStatus::InvalidNoc),
            };
        }

        let index = table.allocate_index().map_err(|_| Status::Failure)?;
        let fabric = Fabric::new(
            index,
            FabricIdentity {
                fabric_id: identity.fabric_id,
                node_id: identity.node_id,
                root_public_key: identity.root_public_key,
                admin_vendor_id: request.admin_vendor_id,
            },
            &SymmetricKey::new(request.ipk),
            pending.key,
            credentials,
        );
        let Ok(fabric) = fabric else {
            return Ok(NocStatus::InvalidNoc);
        };
        if table.insert(fabric).is_err() {
            return Ok(NocStatus::FabricConflict);
        }
        drop(table);
        drop(pending_root);

        // Only now is the pending state consumed: every path above left it intact.
        self.pending_csr.set(None);
        *self.pending_root.borrow_mut() = None;

        // Step 9: "The Fabric Index associated with the armed fail-safe context SHALL be
        // updated to match the Fabric Index just allocated." Without it, the
        // `CommissioningComplete` that follows over CASE on the new fabric would not match.
        let mut fail_safe = self.fail_safe.borrow_mut();
        fail_safe
            .record(ctx.now, |p| p.added_noc = true)
            .map_err(|_| Status::FailsafeRequired)?;
        fail_safe
            .adopt_fabric(index, ctx.now)
            .map_err(|_| Status::FailsafeRequired)?;
        drop(fail_safe);

        self.change.set(Some(FabricChange::Added {
            index,
            case_admin_subject: request.case_admin_subject,
            bind_pase_session: ctx.fabric_index.is_none(),
        }));
        Ok(NocStatus::Ok)
    }

    /// `UpdateNOC` (§11.18.6.9) — rotate the operational key and certificate on a fabric
    /// this node already belongs to.
    pub fn update_noc(
        &self,
        noc: &[u8],
        icac: Option<&[u8]>,
        ctx: &InteractionContext<'_>,
    ) -> Result<NocStatus, Status> {
        let progress = self.require_fail_safe(ctx.now)?;
        if progress.added_noc || progress.updated_noc {
            return Err(Status::ConstraintError);
        }
        // "If a prior AddTrustedRootCertificate command was successfully invoked within the
        // fail-safe timer period, then this command SHALL fail with a CONSTRAINT_ERROR …
        // since the only valid following logical operation is invoking the AddNOC command."
        if progress.added_trusted_root {
            return Err(Status::ConstraintError);
        }
        let Some(pending) = self.pending_csr.get() else {
            return Ok(NocStatus::MissingCsr);
        };
        if pending.session != ctx.session {
            return Ok(NocStatus::MissingCsr);
        }
        // "If the prior CSRRequest state that preceded UpdateNOC had the IsForUpdateNOC field
        // indicated as false, then this command SHALL fail with a CONSTRAINT_ERROR."
        if !pending.for_update {
            return Err(Status::ConstraintError);
        }
        // The command is `AF`, so §8.8.2.3 step b.v has already refused it without a fabric.
        let accessing = ctx.fabric_index.ok_or(Status::UnsupportedAccess)?;

        let mut table = self.fabrics.borrow_mut();
        let Some(existing) = table.find(accessing) else {
            return Ok(NocStatus::InvalidFabricIndex);
        };
        let rcac = existing.credentials.rcac.clone();
        let existing_fabric_id = existing.fabric_id;

        let identity = match validate_chain(noc, icac, &rcac, &pending.public) {
            Ok(identity) => identity,
            Err(status) => return Ok(status),
        };
        // "The NOC provided in the NOCValue does not refer in its subject to the FabricID
        // associated with the accessing fabric" — and the same for the ICAC.
        if identity.fabric_id != existing_fabric_id {
            return Ok(NocStatus::InvalidNoc);
        }

        let mut credentials = match Credentials::new(noc, &rcac) {
            Ok(credentials) => credentials,
            Err(_) => return Ok(NocStatus::InvalidNoc),
        };
        if let Some(icac) = icac {
            credentials = match credentials.with_icac(icac) {
                Ok(credentials) => credentials,
                Err(_) => return Ok(NocStatus::InvalidNoc),
            };
        }

        let Some(fabric) = table.find_mut(accessing) else {
            return Ok(NocStatus::InvalidFabricIndex);
        };
        let previous_key = fabric.operational_key;
        fabric.node_id = identity.node_id;
        fabric.credentials = credentials;
        fabric.operational_key = pending.key;
        drop(table);

        // Step 1.c: "All internal data reflecting the prior operational identifier … SHALL be
        // revoked and removed." The previous operational key is the first of those, and it is
        // the one whose survival would silently keep the old identity usable.
        let _ = self.keys.borrow_mut().remove(previous_key);
        self.pending_csr.set(None);

        self.fail_safe
            .borrow_mut()
            .record(ctx.now, |p| p.updated_noc = true)
            .map_err(|_| Status::FailsafeRequired)?;
        self.change
            .set(Some(FabricChange::Updated { index: accessing }));
        Ok(NocStatus::Ok)
    }

    /// `UpdateFabricLabel` (§11.18.6.11).
    pub fn update_fabric_label(
        &self,
        label: &str,
        ctx: &InteractionContext<'_>,
    ) -> Result<NocStatus, Status> {
        let accessing = ctx.fabric_index.ok_or(Status::UnsupportedAccess)?;
        let mut table = self.fabrics.borrow_mut();
        // "If the Label field is identical to a Label already in use by a Fabric within the
        // Fabrics list **that is not the accessing fabric** … LabelConflict."
        if table
            .iter()
            .any(|f| f.index != accessing && f.label.as_str() == label && !label.is_empty())
        {
            return Ok(NocStatus::LabelConflict);
        }
        let Some(fabric) = table.find_mut(accessing) else {
            return Ok(NocStatus::InvalidFabricIndex);
        };
        // "max 32" — longer is a constraint error, not a truncation.
        fabric
            .set_label(label)
            .map_err(|_| Status::ConstraintError)?;
        Ok(NocStatus::Ok)
    }

    /// `RemoveFabric` (§11.18.6.12) — leave a fabric, and delete everything scoped to it.
    ///
    /// The index is a *parameter*, not the accessing fabric: an administrator may remove a
    /// fabric other than its own, which is why the command is `A` rather than `AF`. The three
    /// outcomes §11.18.6.12 distinguishes differ only in what else goes with it, and
    /// [`FabricChange::Removed`] carries which one happened.
    pub fn remove_fabric(
        &self,
        index: FabricIndex,
        ctx: &InteractionContext<'_>,
    ) -> Result<NocStatus, Status> {
        let mut table = self.fabrics.borrow_mut();
        // "If the FabricIndex field does not match the FabricIndex of any entry within the
        // Fabrics list, then an NOCResponse with a StatusCode of InvalidFabricIndex SHALL be
        // returned … and there SHALL NOT be any permanent changes to any device data."
        let Some(removed) = table.remove(index) else {
            return Ok(NocStatus::InvalidFabricIndex);
        };
        let was_last = table.is_empty();
        drop(table);

        // The operational key has to actually be destroyed, not merely forgotten: a fabric
        // whose key survived removal could still be impersonated by anything that reaches the
        // key store.
        let _ = self.keys.borrow_mut().remove(removed.operational_key);

        self.change.set(Some(FabricChange::Removed {
            index,
            was_last,
            was_accessing: ctx.fabric_index == Some(index),
        }));
        Ok(NocStatus::Ok)
    }

    /// `SetVIDVerificationStatement` (§11.18.6.14).
    ///
    /// All three fields are optional and at least one must be present (`O.a+`). The command
    /// "SHALL only operate against the Fabrics and NOCs attribute entries associated with the
    /// accessing fabric index", which is what `AF` enforces before it reaches here.
    pub fn set_vid_verification_statement(
        &self,
        vendor_id: Option<VendorId>,
        statement: Option<&[u8]>,
        vvsc: Option<&[u8]>,
        ctx: &InteractionContext<'_>,
    ) -> Result<(), Status> {
        if vendor_id.is_none() && statement.is_none() && vvsc.is_none() {
            // `O.a+`: "at least one of the marked fields SHALL be present".
            return Err(Status::InvalidCommand);
        }
        let accessing = ctx.fabric_index.ok_or(Status::UnsupportedAccess)?;
        let mut table = self.fabrics.borrow_mut();
        let Some(fabric) = table.find_mut(accessing) else {
            return Err(Status::ConstraintError);
        };

        if let Some(statement) = statement {
            match statement.len() {
                // "If the length of the field's value is exactly 0, then the
                // VIDVerificationStatement field … SHALL be erased."
                0 => fabric.vid_verification_statement = None,
                VID_VERIFICATION_STATEMENT_LEN => {
                    let mut value = [0u8; VID_VERIFICATION_STATEMENT_LEN];
                    value.copy_from_slice(statement);
                    fabric.vid_verification_statement = Some(value);
                }
                // "If the length … is neither exactly 0 nor exactly 85, then the command
                // SHALL fail with a status code of CONSTRAINT_ERROR."
                _ => return Err(Status::ConstraintError),
            }
        }
        if let Some(vvsc) = vvsc {
            // A VVSC alongside an ICAC is INVALID_COMMAND, which `set_vvsc` reports as an
            // argument error (§11.18.4.4's mutual exclusion).
            fabric
                .credentials
                .set_vvsc(vvsc)
                .map_err(|_| Status::InvalidCommand)?;
        }
        if let Some(vendor_id) = vendor_id {
            fabric.admin_vendor_id = vendor_id;
        }
        Ok(())
    }

    /// `SignVIDVerificationRequest` (§11.18.6.15) → `SignVIDVerificationResponse`
    /// (§11.18.6.16).
    ///
    /// Signs §6.4.10's `vendor_id_verification_tbs` with the *operational* key of the fabric
    /// under verification — not the attestation key. The procedure proves that whoever holds
    /// that fabric's NOC stands behind the `VendorID` the fabric claims, which is a statement
    /// about the fabric rather than about the hardware.
    pub fn sign_vid_verification(
        &self,
        index: FabricIndex,
        client_challenge: &[u8; 32],
        ctx: &InteractionContext<'_>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let challenge = ctx.attestation_challenge.ok_or(Status::UnsupportedAccess)?;
        let table = self.fabrics.borrow();
        // "If the FabricIndex field contains a fabric index which does not have an associated
        // entry in the Fabrics attribute, then the command SHALL fail with a status code of
        // CONSTRAINT_ERROR."
        let fabric = table.find(index).ok_or(Status::ConstraintError)?;

        let mut tbs_buf = [0u8; VENDOR_ID_VERIFICATION_TBS_MAX];
        let tbs = fabric.vendor_id_verification_tbs(&mut tbs_buf, client_challenge, challenge);
        let signature = self
            .keys
            .borrow()
            .sign(fabric.operational_key, tbs)
            .map_err(|_| Status::Failure)?;

        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        full(w.start_structure(tag))?;
        full(w.unsigned(Tag::Context(0), u64::from(index.0)))?;
        full(w.unsigned(
            Tag::Context(1),
            u64::from(crate::fabric::FABRIC_BINDING_VERSION),
        ))?;
        full(w.octets(Tag::Context(2), signature.as_bytes()))?;
        full(w.end_container())
    }
}

/// Whether a value is a valid access-control subject for `AuthMode: CASE` (§6.6.2.1.1).
///
/// §11.18.6.8: "not being in either the Operational or CASE Authenticated Tag range" is
/// `InvalidAdminSubject`. A group node id or a zero would name something that can never
/// authenticate over CASE, leaving the new fabric joined and unadministrable.
fn is_case_subject(subject: u64) -> bool {
    let node = NodeId(subject);
    matches!(
        node.kind(),
        crate::msg::NodeIdKind::Operational | crate::msg::NodeIdKind::CaseAuthenticatedTag
    )
}

/// The identity a validated chain attests to.
struct ChainIdentity {
    fabric_id: crate::msg::FabricId,
    node_id: NodeId,
    root_public_key: PublicKey,
}

/// §11.18.6.7's three validation steps, in the order the specification numbers them.
fn validate_chain(
    noc: &[u8],
    icac: Option<&[u8]>,
    rcac: &[u8],
    expected_public_key: &PublicKey,
) -> Result<ChainIdentity, NocStatus> {
    let noc_cert = MatterCertificate::decode(noc).map_err(|_| NocStatus::InvalidNoc)?;
    let icac_cert = match icac {
        Some(bytes) => Some(MatterCertificate::decode(bytes).map_err(|_| NocStatus::InvalidNoc)?),
        None => None,
    };
    let root = MatterCertificate::decode(rcac).map_err(|_| NocStatus::InvalidNoc)?;

    // Step 3, hoisted: "The DN Encoding Rules SHALL be validated for every certificate in the
    // chain, including valid value range checks for identifiers such as Fabric ID and Node
    // ID … the error status SHALL be InvalidNodeOpId if the matter-node-id attribute in the
    // subject DN of the NOC has a value outside the Operational Node ID range". That check
    // has to come before the chain verification, because a NOC with no node id at all would
    // otherwise fail as a generic InvalidNOC and hide what was actually wrong.
    let node_id = noc_cert.node_id().ok_or(NocStatus::InvalidNodeOpId)?;
    if !node_id.is_operational() {
        return Err(NocStatus::InvalidNodeOpId);
    }

    // Step 1: Crypto_VerifyChain over the whole chain. `at = None` — a commissionee has no
    // wall clock during commissioning, and §6.4.5 only requires the validity window to be
    // checked when the node knows the time.
    let verified = crate::cert::verify_chain(&noc_cert, icac_cert.as_ref(), &root, None)
        .map_err(|_| NocStatus::InvalidNoc)?;

    // Step 2: "The public key of the NOC SHALL match the last generated operational public
    // key on this session … If this check fails, the error status SHALL be InvalidPublicKey."
    //
    // This is the step that ties the certificate to a key the *device* made. Without it an
    // administrator could install a NOC over a key pair it generated itself and then
    // impersonate the node.
    if noc_cert.public_key.as_bytes() != expected_public_key.as_bytes() {
        return Err(NocStatus::InvalidPublicKey);
    }

    Ok(ChainIdentity {
        fabric_id: verified.fabric_id,
        node_id,
        root_public_key: root.public_key,
    })
}

// --- The attributes ----------------------------------------------------------------------------

/// The global `FabricIndex` field of a fabric-scoped struct (§7.19.1.9).
///
/// > A fabric-scoped struct SHALL support the global FabricIndex field of type fabric-index,
/// > which indicates the associated fabric of the struct … The table that defines fields of a
/// > fabric-scoped struct SHALL NOT list the global FabricIndex field, which is a global field
/// > and defined implicitly.
///
/// Which is why it is not in §11.18.4.4's or §11.18.4.5's tables and must still be emitted.
pub const FABRIC_INDEX_FIELD: u8 = 254;

impl<C: Config, K: KeyStore, R: Rng, const N: usize> OperationalCredentials<'_, C, K, R, N> {
    /// Whether a fabric's entries belong in this read (§7.19.1.8.2).
    ///
    /// > For a read interaction on a list, with fabric-filtering disabled, the list SHALL be
    /// > reported as a full list with all entries.
    ///
    /// With filtering enabled, only the accessing fabric's. A request with filtering on and
    /// *no* accessing fabric — a PASE session — matches nothing, which is right: there is no
    /// fabric whose entries it is asking for.
    fn visible(ctx: &InteractionContext<'_>, index: FabricIndex) -> bool {
        !ctx.fabric_filtered || ctx.fabric_index == Some(index)
    }

    fn write_nocs(
        &self,
        ctx: &InteractionContext<'_>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        let table = self.fabrics.borrow();
        full(w.start_array(tag))?;
        for fabric in table.iter().filter(|f| Self::visible(ctx, f.index)) {
            let credentials = &fabric.credentials;
            full(w.start_structure(Tag::Anonymous))?;
            full(w.octets(Tag::Context(1), &credentials.noc))?;
            // §11.18.4.4: "If no ICAC is present in the chain, this field SHALL be set to
            // null" — present-and-null, not absent.
            match &credentials.icac {
                Some(icac) => full(w.octets(Tag::Context(2), icac))?,
                None => full(w.null(Tag::Context(2)))?,
            }
            // "If no VVSC is needed, this field SHALL be omitted (in that there SHALL NOT be
            // a value present, not even an empty octet string)." The opposite convention from
            // the ICAC, in the same structure.
            if let Some(vvsc) = &credentials.vvsc {
                full(w.octets(Tag::Context(3), vvsc))?;
            }
            full(w.unsigned(Tag::Context(FABRIC_INDEX_FIELD), u64::from(fabric.index.0)))?;
            full(w.end_container())?;
        }
        full(w.end_container())
    }

    fn write_fabrics(
        &self,
        ctx: &InteractionContext<'_>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        let table = self.fabrics.borrow();
        full(w.start_array(tag))?;
        for fabric in table.iter().filter(|f| Self::visible(ctx, f.index)) {
            full(w.start_structure(Tag::Anonymous))?;
            full(w.octets(Tag::Context(1), fabric.root_public_key.as_bytes()))?;
            full(w.unsigned(Tag::Context(2), u64::from(fabric.admin_vendor_id.0)))?;
            full(w.unsigned(Tag::Context(3), fabric.fabric_id.0))?;
            full(w.unsigned(Tag::Context(4), fabric.node_id.0))?;
            full(w.utf8(Tag::Context(5), fabric.label.as_str()))?;
            if let Some(statement) = &fabric.vid_verification_statement {
                full(w.octets(Tag::Context(6), statement))?;
            }
            full(w.unsigned(Tag::Context(FABRIC_INDEX_FIELD), u64::from(fabric.index.0)))?;
            full(w.end_container())?;
        }
        full(w.end_container())
    }

    /// `TrustedRootCertificates` (§11.18.5.5) — a plain `list[octstr]`, *not* fabric-scoped.
    ///
    /// "Depending on the method of storage employed by the server, either shared storage for
    /// identical root certificates shared by many fabrics, or individually stored root
    /// certificate per fabric, **multiple identical root certificates MAY legally appear
    /// within the list**." This implementation stores one per fabric, so duplicates do
    /// appear — and §11.18.5.5's own advice is how a client copes: "To match a root with a
    /// given fabric, the root certificate's subject and subject public key need to be
    /// cross-referenced with the NOC or ICAC certificates".
    fn write_roots(
        &self,
        w: &mut TlvWriter<'_>,
        tag: Tag,
        now: crate::platform::Instant,
    ) -> Result<(), Status> {
        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        let table = self.fabrics.borrow();
        full(w.start_array(tag))?;
        for fabric in table.iter() {
            full(w.octets(Tag::Anonymous, &fabric.credentials.rcac))?;
        }
        // §11.18.6.13: `AddTrustedRootCertificate` "SHALL add a Trusted Root CA Certificate …
        // **to the TrustedRootCertificates Attribute list**". Present tense, and the list is
        // the attribute — so the root appears the moment the command succeeds, not when
        // `AddNOC` commits it to a fabric. An administrator adds the root, reads the attribute
        // back to confirm the node took it, and only then sends `AddNOC`; a node that lists
        // committed roots only answers that read with the root missing, having just said
        // SUCCESS.
        //
        // It cannot be counted twice: `AddNOC` clears the pending root as it commits it, and
        // so does the fail-safe's rollback.
        //
        // Only while the fail-safe that added it is armed. §11.10.7.2.2 step 9 removes trusted
        // roots no fabric references when the fail-safe ends, so a pending root outside a
        // fail-safe period is not pending — it is garbage waiting for `reap`, which runs on
        // the next *invoke*. A read that arrives first would otherwise report a root the node
        // has already promised to have dropped, which is what `TC_OPCREDS_3_1` checks
        // immediately after `ArmFailSafe(0)`.
        // …and only while the fail-safe that added it is *the one still armed*, which is
        // exactly the condition `reap` applies: `progress.added_trusted_root` is true only for
        // the context that accepted this root. Asking merely whether *some* fail-safe is armed
        // is not enough — the next `ArmFailSafe` would bring the abandoned root back from the
        // dead, and `ArmFailSafe` belongs to General Commissioning, so no invoke against this
        // cluster need happen in between to reap it.
        if self
            .fail_safe
            .borrow()
            .armed(now)
            .is_some_and(|armed| armed.progress.added_trusted_root)
            && let Some(pending) = self.pending_root.borrow().as_ref()
        {
            full(w.octets(Tag::Anonymous, pending))?;
        }
        full(w.end_container())
    }
}

impl<C: Config, K: KeyStore, R: Rng, const N: usize> ClusterHandler
    for OperationalCredentials<'_, C, K, R, N>
{
    fn read(
        &self,
        resolved: &Resolved<'_>,
        ctx: &InteractionContext<'_>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        match resolved.attribute {
            NOCS => self.write_nocs(ctx, w, tag),
            FABRICS => self.write_fabrics(ctx, w, tag),
            // Both are `uint8`, and `AssertValid` holds `Config::FABRICS` to §11.18.5.3's
            // `5 to 254` at compile time — so the conversion cannot lose anything, and
            // saturating rather than panicking is the right way to say so on a device.
            SUPPORTED_FABRICS => {
                let capacity = u8::try_from(self.fabrics.borrow().capacity()).unwrap_or(u8::MAX);
                full(w.unsigned(tag, u64::from(capacity)))
            }
            COMMISSIONED_FABRICS => {
                let len = u8::try_from(self.fabrics.borrow().len()).unwrap_or(u8::MAX);
                full(w.unsigned(tag, u64::from(len)))
            }
            TRUSTED_ROOT_CERTIFICATES => self.write_roots(w, tag, ctx.now),
            // §11.18.5.6: "This attribute SHALL indicate the accessing fabric index", whose
            // fallback is 0 — the value that means "no fabric", which is exactly what a PASE
            // session has.
            CURRENT_FABRIC_INDEX => {
                full(w.unsigned(tag, u64::from(ctx.fabric_index.unwrap_or(FabricIndex(0)).0)))
            }
            _ => Err(Status::UnsupportedAttribute),
        }
    }

    fn invoke(
        &self,
        resolved: &ResolvedCommand<'_>,
        fields: Option<&[u8]>,
        ctx: &InteractionContext<'_>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<Option<CommandId>, StatusIb> {
        self.run(resolved.command.id, fields, ctx, w, tag)
            .map_err(StatusIb::from)
    }
}

impl<C: Config, K: KeyStore, R: Rng, const N: usize> Cluster
    for OperationalCredentials<'_, C, K, R, N>
{
    const ID: ClusterId = ID;
}

// --- Command decoding --------------------------------------------------------------------------

/// Reads the members of a `CommandFields` structure, one at a time.
///
/// `CommandFields` is the `CommandDataIB`'s context-1 member (§10.6.11), so it arrives
/// *tagged*: a fragment of a structure rather than a TLV document, and reading it with
/// [`TlvReader::new`] would reject exactly the bytes that are correct.
///
/// Only the structure's own end-of-container ends the walk. A short buffer and a malformed
/// element are both `INVALID_COMMAND`: treating either as an end of input would let a
/// truncated `AddNOC` be read as one with fields absent.
fn walk_fields<'a>(
    fields: Option<&'a [u8]>,
    mut on_field: impl FnMut(u8, &crate::tlv::Element<'a>) -> Result<bool, Status>,
) -> Result<(), Status> {
    let fields = fields.ok_or(Status::InvalidCommand)?;
    let mut reader = TlvReader::new_in(fields, ContainerKind::Structure);
    let element = reader
        .next_element()
        .map_err(|_| Status::InvalidCommand)?
        .ok_or(Status::InvalidCommand)?;
    if element.value.container() != Some(ContainerKind::Structure) {
        return Err(Status::InvalidCommand);
    }
    let start_depth = reader.depth();
    loop {
        let Some(field) = reader.next_element().map_err(|_| Status::InvalidCommand)? else {
            return Err(Status::InvalidCommand);
        };
        if reader.depth() < start_depth {
            break;
        }
        let number = match field.tag {
            Tag::Context(number) => number,
            // A fully-qualified tag is a vendor extension; §11.18 has none, and §10.6.11's
            // forward-compatibility rule is to ignore what is not understood.
            _ => {
                reader
                    .skip_value(&field)
                    .map_err(|_| Status::InvalidCommand)?;
                continue;
            }
        };
        if !on_field(number, &field)? {
            reader
                .skip_value(&field)
                .map_err(|_| Status::InvalidCommand)?;
        }
    }
    Ok(())
}

fn decode_nonce<const L: usize>(element: &crate::tlv::Element<'_>) -> Result<[u8; L], Status> {
    let bytes = element.octets().map_err(|_| Status::InvalidCommand)?;
    // §11.18.6.1: "If the AttestationNonce that is provided in the command is malformed, a
    // recipient SHALL fail the command with a Status Code of INVALID_COMMAND." A nonce of the
    // wrong length is malformed, not merely constrained: it would change what is signed.
    let mut out = [0u8; L];
    if bytes.len() != L {
        return Err(Status::InvalidCommand);
    }
    out.copy_from_slice(bytes);
    Ok(out)
}

impl<C: Config, K: KeyStore, R: Rng, const N: usize> OperationalCredentials<'_, C, K, R, N> {
    /// Answers a `NOCResponse` (§11.18.6.10): `StatusCode [0]`, `FabricIndex [1]`,
    /// `DebugText [2]`.
    ///
    /// `FabricIndex` is present only on success — its conformance is `StatusCode == OK, O` —
    /// and `DebugText` is omitted entirely: it is optional, and a device that filled it would
    /// leak its internals to anyone who can invoke the command.
    fn noc_response(
        status: NocStatus,
        index: Option<FabricIndex>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<(), Status> {
        let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
        full(w.start_structure(tag))?;
        full(w.unsigned(Tag::Context(0), u64::from(status.value())))?;
        if status.is_ok()
            && let Some(index) = index
        {
            full(w.unsigned(Tag::Context(1), u64::from(index.0)))?;
        }
        full(w.end_container())
    }
}

impl<C: Config, K: KeyStore, R: Rng, const N: usize> OperationalCredentials<'_, C, K, R, N> {
    /// Runs one command of §11.18.6.
    ///
    /// This is what [`ClusterHandler::invoke`] forwards to; it is public because the
    /// commands are worth driving directly from a test or a controller-side harness.
    pub fn run(
        &self,
        command: CommandId,
        fields: Option<&[u8]>,
        ctx: &InteractionContext<'_>,
        w: &mut TlvWriter<'_>,
        tag: Tag,
    ) -> Result<Option<CommandId>, Status> {
        // Anything left over from a fail-safe period that has ended must not be adopted by
        // this one.
        self.reap(ctx.now);

        match command {
            ATTESTATION_REQUEST => {
                let mut nonce = None;
                walk_fields(fields, |number, element| match number {
                    0 => {
                        set_once(
                            &mut nonce,
                            decode_nonce::<{ attestation::ATTESTATION_NONCE_LEN }>(element)?,
                        )
                        .map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    _ => Ok(false),
                })?;
                let nonce = nonce.ok_or(Status::InvalidCommand)?;
                let challenge = ctx.attestation_challenge.ok_or(Status::UnsupportedAccess)?;
                // §11.18.4.7: "The timestamp field SHALL be in epoch-s." A node with no
                // wall clock reports zero, which is what `Clock::utc` returning `None` means
                // and what every commissioner already tolerates.
                self.attestation_response(&nonce, 0, challenge, w, tag)?;
                Ok(Some(ATTESTATION_RESPONSE))
            }
            CERTIFICATE_CHAIN_REQUEST => {
                let mut kind = None;
                walk_fields(fields, |number, element| match number {
                    0 => {
                        let value = element.unsigned().map_err(|_| Status::InvalidCommand)?;
                        let value = u8::try_from(value).map_err(|_| Status::InvalidCommand)?;
                        let kind_value = CertificateChainType::from_value(value)
                            .ok_or(Status::InvalidCommand)?;
                        set_once(&mut kind, kind_value).map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    _ => Ok(false),
                })?;
                let certificate = match kind.ok_or(Status::InvalidCommand)? {
                    CertificateChainType::Dac => self.attestation.dac,
                    CertificateChainType::Pai => self.attestation.pai,
                };
                let full = |r: crate::error::Result<()>| r.map_err(|_| Status::ResourceExhausted);
                full(w.start_structure(tag))?;
                full(w.octets(Tag::Context(0), certificate))?;
                full(w.end_container())?;
                Ok(Some(CERTIFICATE_CHAIN_RESPONSE))
            }
            CSR_REQUEST => {
                let mut nonce = None;
                let mut for_update = None;
                walk_fields(fields, |number, element| match number {
                    0 => {
                        set_once(
                            &mut nonce,
                            decode_nonce::<{ attestation::CSR_NONCE_LEN }>(element)?,
                        )
                        .map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    1 => {
                        let value = element.bool().map_err(|_| Status::InvalidCommand)?;
                        set_once(&mut for_update, value).map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    _ => Ok(false),
                })?;
                let nonce = nonce.ok_or(Status::InvalidCommand)?;
                // `IsForUpdateNOC` is optional with a fallback of false.
                let mut random = [0u8; 32];
                self.rng
                    .borrow_mut()
                    .fill(&mut random)
                    .map_err(|_| Status::Failure)?;
                self.csr_response(&nonce, for_update.unwrap_or(false), ctx, &random, w, tag)?;
                Ok(Some(CSR_RESPONSE))
            }
            ADD_NOC => {
                let mut noc = None;
                let mut icac = None;
                let mut ipk = None;
                let mut subject = None;
                let mut vendor = None;
                walk_fields(fields, |number, element| {
                    match number {
                        0 => set_once(
                            &mut noc,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        ),
                        1 => set_once(
                            &mut icac,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        ),
                        2 => set_once(
                            &mut ipk,
                            decode_nonce::<{ crate::crypto::SYMMETRIC_KEY_LENGTH_BYTES }>(element)?,
                        ),
                        3 => set_once(
                            &mut subject,
                            element.unsigned().map_err(|_| Status::InvalidCommand)?,
                        ),
                        4 => {
                            let value = element.unsigned().map_err(|_| Status::InvalidCommand)?;
                            let value =
                                u16::try_from(value).map_err(|_| Status::ConstraintError)?;
                            set_once(&mut vendor, VendorId(value))
                        }
                        _ => return Ok(false),
                    }
                    .map_err(|_| Status::InvalidCommand)?;
                    Ok(true)
                })?;
                let request = AddNocRequest {
                    noc: noc.ok_or(Status::InvalidCommand)?,
                    icac,
                    ipk: ipk.ok_or(Status::InvalidCommand)?,
                    case_admin_subject: subject.ok_or(Status::InvalidCommand)?,
                    admin_vendor_id: vendor.ok_or(Status::InvalidCommand)?,
                };
                let status = self.add_noc(&request, ctx)?;
                Self::noc_response(status, self.changed_index(), w, tag)?;
                Ok(Some(NOC_RESPONSE))
            }
            UPDATE_NOC => {
                let mut noc = None;
                let mut icac = None;
                walk_fields(fields, |number, element| {
                    match number {
                        0 => set_once(
                            &mut noc,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        ),
                        1 => set_once(
                            &mut icac,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        ),
                        _ => return Ok(false),
                    }
                    .map_err(|_| Status::InvalidCommand)?;
                    Ok(true)
                })?;
                let status = self.update_noc(noc.ok_or(Status::InvalidCommand)?, icac, ctx)?;
                Self::noc_response(status, self.changed_index(), w, tag)?;
                Ok(Some(NOC_RESPONSE))
            }
            UPDATE_FABRIC_LABEL => {
                let mut label = None;
                walk_fields(fields, |number, element| match number {
                    0 => {
                        set_once(
                            &mut label,
                            element.utf8().map_err(|_| Status::InvalidCommand)?,
                        )
                        .map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    _ => Ok(false),
                })?;
                let status = self.update_fabric_label(label.ok_or(Status::InvalidCommand)?, ctx)?;
                Self::noc_response(status, ctx.fabric_index, w, tag)?;
                Ok(Some(NOC_RESPONSE))
            }
            REMOVE_FABRIC => {
                let mut index = None;
                walk_fields(fields, |number, element| match number {
                    0 => {
                        let value = element.unsigned().map_err(|_| Status::InvalidCommand)?;
                        let value = u8::try_from(value).map_err(|_| Status::ConstraintError)?;
                        set_once(&mut index, FabricIndex(value))
                            .map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    _ => Ok(false),
                })?;
                let index = index.ok_or(Status::InvalidCommand)?;
                let status = self.remove_fabric(index, ctx)?;
                Self::noc_response(status, Some(index), w, tag)?;
                Ok(Some(NOC_RESPONSE))
            }
            ADD_TRUSTED_ROOT_CERTIFICATE => {
                let mut rcac = None;
                walk_fields(fields, |number, element| match number {
                    0 => {
                        set_once(
                            &mut rcac,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        )
                        .map_err(|_| Status::InvalidCommand)?;
                        Ok(true)
                    }
                    _ => Ok(false),
                })?;
                self.add_trusted_root(rcac.ok_or(Status::InvalidCommand)?, ctx)?;
                // No response command: §11.18.6's table gives `Y`, so success is a plain
                // SUCCESS status.
                Ok(None)
            }
            SET_VID_VERIFICATION_STATEMENT => {
                let mut vendor = None;
                let mut statement = None;
                let mut vvsc = None;
                walk_fields(fields, |number, element| {
                    match number {
                        0 => {
                            let value = element.unsigned().map_err(|_| Status::InvalidCommand)?;
                            let value =
                                u16::try_from(value).map_err(|_| Status::ConstraintError)?;
                            set_once(&mut vendor, VendorId(value))
                        }
                        1 => set_once(
                            &mut statement,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        ),
                        2 => set_once(
                            &mut vvsc,
                            element.octets().map_err(|_| Status::InvalidCommand)?,
                        ),
                        _ => return Ok(false),
                    }
                    .map_err(|_| Status::InvalidCommand)?;
                    Ok(true)
                })?;
                self.set_vid_verification_statement(vendor, statement, vvsc, ctx)?;
                Ok(None)
            }
            SIGN_VID_VERIFICATION_REQUEST => {
                let mut index = None;
                let mut challenge = None;
                walk_fields(fields, |number, element| {
                    match number {
                        0 => {
                            let value = element.unsigned().map_err(|_| Status::InvalidCommand)?;
                            let value = u8::try_from(value).map_err(|_| Status::ConstraintError)?;
                            set_once(&mut index, FabricIndex(value))
                        }
                        1 => set_once(&mut challenge, decode_nonce::<32>(element)?),
                        _ => return Ok(false),
                    }
                    .map_err(|_| Status::InvalidCommand)?;
                    Ok(true)
                })?;
                self.sign_vid_verification(
                    index.ok_or(Status::InvalidCommand)?,
                    &challenge.ok_or(Status::InvalidCommand)?,
                    ctx,
                    w,
                    tag,
                )?;
                Ok(Some(SIGN_VID_VERIFICATION_RESPONSE))
            }
            _ => Err(Status::UnsupportedCommand),
        }
    }

    /// The index the change just recorded touched, without consuming it.
    fn changed_index(&self) -> Option<FabricIndex> {
        match self.change.get()? {
            FabricChange::Added { index, .. }
            | FabricChange::Updated { index }
            | FabricChange::Removed { index, .. } => Some(index),
        }
    }
}
