//! The IR, written out as Rust.
//!
//! One module per cluster, one per device type, and a `mod.rs` that names them. Everything is
//! `const`, macro-free and sorted: `const` so a device pays only for what it references,
//! macro-free so rustc scales linearly with 128 clusters rather than quadratically, and sorted
//! so `cargo xtask check` compares a byte at a time.

use std::fmt::Write as _;

use crate::ident;
use crate::model::{
    Attribute, Bitmap, Cluster, Command, Condition, Conform, DataModel, Enumeration, Event, Field,
    Structure, Verdict,
};
use crate::types::{Resolved, Types};

/// The banner every generated file carries.
fn header(version: &str, what: &str) -> String {
    format!(
        "// Generated by `cargo xtask` from the CSA data model {version}. Do not edit.\n\
         //\n\
         // {what}\n\
         //\n\
         // Regenerate with `cargo xtask clusters --dm <checkout>/data_model/{version}`; \
         `cargo xtask check`\n\
         // is the CI gate that keeps this file honest. The XML itself is not vendored here \
         — it\n\
         // carries the CSA's own copyright notice and is not redistributable.\n\n"
    )
}

/// Generates every file. The key is a filename relative to the output directory.
pub fn emit(model: &DataModel) -> Vec<(String, String)> {
    let mut files = Vec::new();
    let mut cluster_modules: Vec<(String, &Cluster)> = Vec::new();
    let mut names: Vec<String> = model
        .clusters
        .iter()
        .map(|cluster| ident::snake(&cluster.name))
        .collect();
    ident::unique(&mut names);
    let module_of: std::collections::BTreeMap<u32, String> = model
        .clusters
        .iter()
        .map(|c| c.id)
        .zip(names.iter().cloned())
        .collect();
    let types = Types::index(model, &module_of);
    for (name, cluster) in names.iter().zip(&model.clusters) {
        files.push((
            format!("{name}.rs"),
            cluster_file(model, cluster, name, &types),
        ));
        cluster_modules.push((name.clone(), cluster));
    }

    let mut device_names: Vec<String> = model
        .device_types
        .iter()
        .map(|device| ident::snake(&device.name))
        .collect();
    ident::unique(&mut device_names);
    files.push((
        "device_types.rs".to_owned(),
        device_types_file(model, &device_names),
    ));

    files.push(("mod.rs".to_owned(), mod_file(model, &cluster_modules)));
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

// --- mod.rs -------------------------------------------------------------------------------

fn mod_file(model: &DataModel, modules: &[(String, &Cluster)]) -> String {
    let mut out = header(&model.version, "Every cluster the specification defines.");
    out.push_str(
        "//! The Matter cluster library, generated from the CSA data model.\n\
         //!\n\
         //! One module per cluster. Each holds the cluster's identifiers, its feature bits,\n\
         //! its enumerations and bitmaps as Rust types, and a [`Cluster`](crate::dm::spec::Cluster)\n\
         //! carrying every element the specification defines with its conformance, access and\n\
         //! qualities.\n\
         //!\n\
         //! These are the specification's tables, not a device's configuration. What a device\n\
         //! serves is a [`ClusterDescriptor`](crate::dm::ClusterDescriptor), and\n\
         //! [`Cluster::validate`](crate::dm::spec::Cluster::validate) is what checks one\n\
         //! against the other — the drift that certification finds, found at home instead.\n\n",
    );
    for (name, cluster) in modules {
        if cluster.is_base {
            let _ = writeln!(
                out,
                "/// {} — an abstract base: the types the clusters derived from it share,\n\
                 /// with no cluster id of its own.\npub mod {name};",
                ident::doc(&cluster.name),
            );
        } else {
            let _ = writeln!(
                out,
                "/// {} — cluster `{:#06X}`.\npub mod {name};",
                ident::doc(&cluster.name),
                cluster.id
            );
        }
    }
    out.push_str("\npub mod device_types;\n\n");

    out.push_str(
        "/// Every cluster in the library, sorted by id.\n\
         ///\n\
         /// **Referencing this links all of them.** Each table on its own is `const` data the\n\
         /// linker drops when nothing names it — one cluster costs about 8 KB of read-only\n\
         /// data, the whole library about 131 KB, measured on a release build. So a\n\
         /// controller or a conformance tool uses `ALL` and pays for it happily, and a device\n\
         /// names the handful of clusters it serves and pays for those.\n\
         ///\n\
         /// [`crate::clusters::validate_endpoint`] reaches `ALL` through [`find`], which is\n\
         /// why it belongs in a device's *tests* rather than its start-up path.\n",
    );
    let _ = writeln!(
        out,
        "pub const ALL: &[&crate::dm::spec::Cluster] = &[\n{}];\n",
        modules
            .iter()
            .filter(|(_, cluster)| !cluster.is_base)
            .map(|(name, _)| format!("    &{name}::CLUSTER,\n"))
            .collect::<String>()
    );

    out.push_str(
        "/// The specification's definition of a cluster, by id.\n\
         ///\n\
         /// Linear over 128 entries, which is nothing next to what a caller does with the\n\
         /// answer — and a sorted binary search would be one `unsafe`-free `expect` away from\n\
         /// a table that is sorted by construction anyway.\n\
         #[must_use]\n\
         pub fn find(id: crate::im::ClusterId) -> Option<&'static crate::dm::spec::Cluster> {\n\
         \x20   ALL.iter().copied().find(|cluster| cluster.id == id)\n\
         }\n",
    );
    out
}

// --- One cluster ----------------------------------------------------------------------------

fn cluster_file(model: &DataModel, cluster: &Cluster, module: &str, types: &Types) -> String {
    let mut out = header(
        &model.version,
        &format!(
            "{} — cluster {:#06X}.",
            ident::doc(&cluster.name),
            cluster.id
        ),
    );
    let _ = writeln!(
        out,
        "//! {} (cluster `{:#06X}`, revision {}).\n//!\n\
         //! {} identifiers, {} feature bits, and the specification's own conformance for\n\
         //! every element. `CLUSTER` is the whole table.\n",
        ident::doc(&cluster.name),
        cluster.id,
        cluster.revision,
        cluster.attributes.len() + cluster.commands.len() + cluster.events.len(),
        cluster.features.len(),
    );
    let _ = writeln!(out, "#![allow(unused_imports)]\n");
    out.push_str(
        "use crate::dm::conformance::{Clause, Condition, Conform, Conformance};\n\
         use crate::dm::meta::{EventPriority, Reporting};\n\
         use crate::dm::spec::{Attribute, Cluster, Command, Event, Feature};\n\
         use crate::dm::{Access, AccessQualities, AttributeQualities, Privilege};\n\
         use crate::error::Result;\n\
         use crate::im::{AttributeId, ClusterId, CommandId, EventId};\n\
         use crate::tlv::{\n\
         \x20   ContainerKind, Element, FromTlv, Nullable, Tag, TlvList, TlvReader, ToTlv, \
         TlvWriter, Value,\n\
         };\n\n",
    );
    let _ = writeln!(
        out,
        "/// The cluster id.\npub const ID: ClusterId = {:#06X};\n",
        cluster.id
    );
    let _ = writeln!(
        out,
        "/// The highest revision the specification's history defines — what `ClusterRevision`\n\
         /// must report (Core §7.13.1).\npub const REVISION: u16 = {};\n",
        cluster.revision
    );
    if !cluster.pics.is_empty() {
        let _ = writeln!(
            out,
            "/// The PICS code, which a certification declaration names the cluster by.\n\
             pub const PICS: &str = {:?};\n",
            cluster.pics
        );
    }

    emit_features(&mut out, cluster);
    emit_ids(&mut out, cluster);
    emit_enums(&mut out, cluster);
    emit_bitmaps(&mut out, cluster);
    emit_structs(&mut out, cluster, types);
    emit_payloads(&mut out, cluster, types);
    if cluster.is_base {
        // An abstract base defines types for the clusters derived from it and is not a
        // cluster anything serves, so it has no table and no entry in `ALL`.
        let _ = module;
        return out;
    }
    emit_tables(&mut out, cluster);
    let _ = writeln!(
        out,
        "/// The whole cluster, as the specification defines it.\n\
         pub const CLUSTER: Cluster = Cluster {{\n\
         \x20   id: ID,\n\
         \x20   name: {:?},\n\
         \x20   revision: REVISION,\n\
         \x20   pics: {:?},\n\
         \x20   derived_from: {},\n\
         \x20   features: FEATURES,\n\
         \x20   attributes: ATTRIBUTES,\n\
         \x20   commands: COMMANDS,\n\
         \x20   events: EVENTS,\n\
         }};",
        cluster.name,
        cluster.pics,
        match &cluster.base_cluster {
            Some(base) => format!("Some({base:?})"),
            None => "None".to_owned(),
        }
    );
    let _ = module;
    out
}

fn emit_features(out: &mut String, cluster: &Cluster) {
    if cluster.features.is_empty() {
        out.push_str(
            "/// This cluster defines no features, so its `FeatureMap` is always zero.\n\
             pub const FEATURES: &[Feature] = &[];\n\n",
        );
        return;
    }
    out.push_str(
        "/// The `FeatureMap` bits (Core §7.13.2).\n\
         ///\n\
         /// A feature has conformance of its own: a device may not claim one the\n\
         /// specification forbids it alongside another.\n\
         pub mod feature {\n",
    );
    let mut names: Vec<String> = cluster
        .features
        .iter()
        .map(|f| ident::screaming(&f.name))
        .collect();
    ident::unique(&mut names);
    for (name, feature) in names.iter().zip(&cluster.features) {
        let summary = if feature.summary.is_empty() {
            format!(
                "`{}`, the cluster's feature bit {}.",
                feature.name, feature.bit
            )
        } else {
            ident::doc(&feature.summary)
        };
        let _ = writeln!(
            out,
            "    /// {summary}\n    ///\n    /// Code `{}`, bit {}.\n    pub const {name}: u32 = 1 << {};",
            feature.code, feature.bit, feature.bit
        );
    }
    out.push_str("}\n\n");

    out.push_str(
        "/// Every feature bit, with its conformance.\npub const FEATURES: &[Feature] = &[\n",
    );
    for feature in &cluster.features {
        let _ = writeln!(
            out,
            "    Feature {{ bit: {}, code: {:?}, name: {:?}, conform: {} }},",
            feature.bit,
            feature.code,
            feature.name,
            conform_expr(cluster, &feature.conform)
        );
    }
    out.push_str("];\n\n");
}

fn emit_ids(out: &mut String, cluster: &Cluster) {
    emit_id_module(
        out,
        "attribute",
        "AttributeId",
        "The attribute ids.",
        cluster
            .attributes
            .iter()
            .map(|a| (a.name.as_str(), a.id, a.summary.as_str())),
    );
    emit_id_module(
        out,
        "command",
        "CommandId",
        "The command ids.",
        cluster
            .commands
            .iter()
            .map(|c| (c.name.as_str(), c.id, c.summary.as_str())),
    );
    emit_id_module(
        out,
        "event",
        "EventId",
        "The event ids.",
        cluster
            .events
            .iter()
            .map(|e| (e.name.as_str(), e.id, e.summary.as_str())),
    );
}

fn emit_id_module<'a>(
    out: &mut String,
    module: &str,
    kind: &str,
    doc: &str,
    entries: impl Iterator<Item = (&'a str, u32, &'a str)>,
) {
    let entries: Vec<_> = entries.collect();
    if entries.is_empty() {
        return;
    }
    let _ = writeln!(out, "/// {doc}\npub mod {module} {{");
    let _ = writeln!(out, "    use crate::im::{kind};\n");
    let mut names: Vec<String> = entries
        .iter()
        .map(|(name, _, _)| ident::screaming(name))
        .collect();
    ident::unique(&mut names);
    for (name, (spec_name, id, summary)) in names.iter().zip(&entries) {
        let width = if *id > 0xFF { 6 } else { 4 };
        // Always a doc line. A generated constant with none is a docs.rs page of bare names,
        // and the specification's own name is the thing a reader is looking for anyway.
        let summary = if summary.is_empty() {
            format!("`{spec_name}`.")
        } else {
            format!("`{spec_name}` — {}", ident::doc(summary))
        };
        let _ = writeln!(out, "    /// {summary}");
        let _ = writeln!(out, "    pub const {name}: {kind} = {id:#0width$X};");
    }
    out.push_str("}\n\n");
}

fn repr_for(max: u64) -> &'static str {
    if max <= u64::from(u8::MAX) {
        "u8"
    } else if max <= u64::from(u16::MAX) {
        "u16"
    } else if max <= u64::from(u32::MAX) {
        "u32"
    } else {
        "u64"
    }
}

fn emit_enums(out: &mut String, cluster: &Cluster) {
    for enumeration in &cluster.enums {
        emit_enum(out, enumeration);
    }
}

fn emit_enum(out: &mut String, enumeration: &Enumeration) {
    let name = ident::pascal(&enumeration.name);
    let max = enumeration.items.iter().map(|i| i.value).max().unwrap_or(0);
    let repr = repr_for(max);
    let mut variants: Vec<String> = enumeration
        .items
        .iter()
        .map(|item| ident::pascal(&item.name))
        .collect();
    ident::unique(&mut variants);

    let _ = writeln!(
        out,
        "/// `{}`.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         #[repr({repr})]\n\
         pub enum {name} {{",
        enumeration.name
    );
    for (variant, item) in variants.iter().zip(&enumeration.items) {
        let summary = if item.summary.is_empty() {
            format!("`{}`.", item.name)
        } else {
            ident::doc(&item.summary)
        };
        let _ = writeln!(out, "    /// {summary}");
        let _ = writeln!(out, "    {variant} = {},", item.value);
    }
    out.push_str("}\n\n");

    // The wire form is an integer, and a value the enumeration does not define is not a
    // decoding error to swallow — §7.19.2's rule is that a reserved value is answered
    // `CONSTRAINT_ERROR`, which is the caller's decision to make from a `None`.
    let _ = writeln!(
        out,
        "impl {name} {{\n\
         \x20   /// Reads a wire value, or `None` for one this revision does not define.\n\
         \x20   #[must_use]\n\
         \x20   pub const fn from_value(value: {repr}) -> Option<Self> {{\n\
         \x20       match value {{"
    );
    for (variant, item) in variants.iter().zip(&enumeration.items) {
        let _ = writeln!(out, "            {} => Some(Self::{variant}),", item.value);
    }
    let _ = writeln!(
        out,
        "            _ => None,\n\
         \x20       }}\n\
         \x20   }}\n\n\
         \x20   /// Its wire value.\n\
         \x20   #[must_use]\n\
         \x20   pub const fn value(self) -> {repr} {{\n\
         \x20       self as {repr}\n\
         \x20   }}\n\
         }}\n"
    );
    // §7.19.2: "a reserved value SHALL be answered CONSTRAINT_ERROR". Decoding one as a
    // variant this revision happens to define would make the device's behaviour depend on
    // what a *future* revision assigns.
    let _ = writeln!(
        out,
        "impl ToTlv for {name} {{\n\
         \x20   fn to_tlv(&self, w: &mut TlvWriter<'_>, tag: Tag) -> Result<()> {{\n\
         \x20       self.value().to_tlv(w, tag)\n\
         \x20   }}\n\
         }}\n\n\
         impl<'a> FromTlv<'a> for {name} {{\n\
         \x20   fn from_tlv(reader: &mut TlvReader<'a>, element: &Element<'a>) -> Result<Self> {{\n\
         \x20       let value = <{repr} as FromTlv<'a>>::from_tlv(reader, element)?;\n\
         \x20       Self::from_value(value)\n\
         \x20           .ok_or(crate::Error::new(crate::ErrorCode::TlvOutOfRange))\n\
         \x20   }}\n\
         }}\n"
    );
}

fn emit_bitmaps(out: &mut String, cluster: &Cluster) {
    for bitmap in &cluster.bitmaps {
        emit_bitmap(out, bitmap);
    }
}

fn emit_bitmap(out: &mut String, bitmap: &Bitmap) {
    let name = ident::pascal(&bitmap.name);
    let max = bitmap
        .fields
        .iter()
        .map(|f| u64::from(f.bit))
        .max()
        .unwrap_or(0);
    let repr = if max < 8 {
        "u8"
    } else if max < 16 {
        "u16"
    } else if max < 32 {
        "u32"
    } else {
        "u64"
    };
    let mut names: Vec<String> = bitmap
        .fields
        .iter()
        .map(|field| ident::screaming(&field.name))
        .collect();
    ident::unique(&mut names);

    let _ = writeln!(
        out,
        "bitflags::bitflags! {{\n\
         \x20   /// `{}`.\n\
         \x20   #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\n\
         \x20   pub struct {name}: {repr} {{",
        bitmap.name
    );
    for (constant, field) in names.iter().zip(&bitmap.fields) {
        let summary = if field.summary.is_empty() {
            format!("`{}`, bit {}.", field.name, field.bit)
        } else {
            ident::doc(&field.summary)
        };
        let _ = writeln!(out, "        /// {summary}");
        let _ = writeln!(out, "        const {constant} = 1 << {};", field.bit);
    }
    out.push_str("    }\n}\n\n");

    // A bit this revision does not define is refused rather than truncated away: §7.19.2's
    // reserved bits "SHALL be set to 0", and quietly clearing one would accept a command a
    // future revision gave a meaning to.
    let _ = writeln!(
        out,
        "impl ToTlv for {name} {{\n\
         \x20   fn to_tlv(&self, w: &mut TlvWriter<'_>, tag: Tag) -> Result<()> {{\n\
         \x20       self.bits().to_tlv(w, tag)\n\
         \x20   }}\n\
         }}\n\n\
         impl<'a> FromTlv<'a> for {name} {{\n\
         \x20   fn from_tlv(reader: &mut TlvReader<'a>, element: &Element<'a>) -> Result<Self> {{\n\
         \x20       let bits = <{repr} as FromTlv<'a>>::from_tlv(reader, element)?;\n\
         \x20       Self::from_bits(bits).ok_or(crate::Error::new(crate::ErrorCode::TlvOutOfRange))\n\
         \x20   }}\n\
         }}\n"
    );
}

// --- The element tables ---------------------------------------------------------------------

fn emit_tables(out: &mut String, cluster: &Cluster) {
    out.push_str("/// Every attribute the specification defines, with its conformance.\npub const ATTRIBUTES: &[Attribute] = &[\n");
    for attribute in &cluster.attributes {
        let _ = writeln!(
            out,
            "    Attribute {{ id: {:#06X}, name: {:?}, kind: {:?}, access: {}, qualities: {}, reporting: {}, conform: {} }},",
            attribute.id,
            attribute.name,
            type_name(attribute),
            access_expr(attribute),
            qualities_expr(attribute),
            reporting_expr(attribute),
            conform_expr(cluster, &attribute.conform)
        );
    }
    out.push_str("];\n\n");

    out.push_str("/// Every command, with its conformance.\npub const COMMANDS: &[Command] = &[\n");
    for command in &cluster.commands {
        // The XML says `commandToServer` or `responseFromServer`; a response belongs in the
        // *generated* list, and accepting one would advertise that a client may invoke this
        // server's own reply.
        let to_server = command.direction != "responseFromServer";
        let response = response_id(cluster, command);
        let _ = writeln!(
            out,
            "    Command {{ id: {:#04X}, name: {:?}, to_server: {to_server}, response: {response}, access: {}, conform: {} }},",
            command.id,
            command.name,
            command_access_expr(command),
            conform_expr(cluster, &command.conform)
        );
    }
    out.push_str("];\n\n");

    out.push_str("/// Every event, with its conformance.\npub const EVENTS: &[Event] = &[\n");
    for event in &cluster.events {
        let priority = match event.priority.as_str() {
            "debug" => "EventPriority::Debug",
            "critical" => "EventPriority::Critical",
            _ => "EventPriority::Info",
        };
        let _ = writeln!(
            out,
            "    Event {{ id: {:#04X}, name: {:?}, priority: {priority}, access: {}, conform: {} }},",
            event.id,
            event.name,
            event_access_expr(event),
            conform_expr(cluster, &event.conform)
        );
    }
    out.push_str("];\n\n");
}

/// The specification's type name for an attribute, list entries included.
fn type_name(attribute: &Attribute) -> String {
    match (&attribute.kind, &attribute.entry) {
        (kind, Some(entry)) if kind == "list" => format!("list[{entry}]"),
        (kind, _) => kind.clone(),
    }
}

/// A response command's id, when the XML names one.
fn response_id(cluster: &Cluster, command: &Command) -> String {
    if command.response.is_empty() || command.response == "Y" || command.response == "N" {
        return "None".to_owned();
    }
    match cluster
        .commands
        .iter()
        .find(|other| other.name == command.response)
    {
        Some(other) => format!("Some({:#04X})", other.id),
        // A response defined in another cluster — the Mode Base derivations do this. The id
        // is not knowable from here, and inventing one would be worse than saying nothing.
        None => "None".to_owned(),
    }
}

fn privilege(name: Option<&String>, fallback: &str) -> String {
    let level = match name.map(String::as_str) {
        Some("view") => "View",
        Some("operate") => "Operate",
        Some("manage") => "Manage",
        Some("admin") => "Administer",
        _ => fallback,
    };
    format!("Privilege::{level}")
}

fn access_qualities(
    fabric_scoped: bool,
    fabric_sensitive: bool,
    timed: bool,
    large: bool,
) -> Option<String> {
    let mut parts = Vec::new();
    if fabric_scoped {
        parts.push("AccessQualities::FABRIC_SCOPED");
    }
    if fabric_sensitive {
        parts.push("AccessQualities::FABRIC_SENSITIVE");
    }
    if timed {
        parts.push("AccessQualities::TIMED");
    }
    if large {
        parts.push("AccessQualities::LARGE");
    }
    if parts.is_empty() {
        None
    } else {
        Some(parts.join(".union(") + &")".repeat(parts.len() - 1))
    }
}

fn access_expr(attribute: &Attribute) -> String {
    let access = &attribute.access;
    let read = privilege(access.read_privilege.as_ref(), "View");
    // Every attribute in the 1.6 library is readable, and §7.6's default when the XML says
    // nothing is `R V`. An unreadable-but-writable one would still be expressible, and this
    // is what would notice it rather than quietly granting a read.
    debug_assert!(access.read || !access.write, "a write-only attribute");
    let base = if access.write {
        format!(
            "Access::read_write_with({read}, {})",
            privilege(access.write_privilege.as_ref(), "Operate")
        )
    } else {
        format!("Access::read_only({read})")
    };
    // An attribute's `L` is not an access constraint: §14.4.5.2 has a large attribute *shrink*
    // on a datagram transport rather than be refused, so gating the read would be wrong.
    match access_qualities(
        access.fabric_scoped,
        access.fabric_sensitive,
        access.timed,
        false,
    ) {
        Some(qualities) => format!("{base}.with_qualities({qualities})"),
        None => base,
    }
}

fn command_access_expr(command: &Command) -> String {
    let base = format!(
        "Access::invoke({})",
        privilege(command.access.invoke_privilege.as_ref(), "Operate")
    );
    match access_qualities(
        command.access.fabric_scoped,
        command.access.fabric_sensitive,
        command.access.timed,
        command.access.large,
    ) {
        Some(qualities) => format!("{base}.with_qualities({qualities})"),
        None => base,
    }
}

fn event_access_expr(event: &Event) -> String {
    let base = format!(
        "Access::read_only({})",
        privilege(event.access.read_privilege.as_ref(), "View")
    );
    match access_qualities(
        event.access.fabric_scoped,
        event.access.fabric_sensitive,
        false,
        false,
    ) {
        Some(qualities) => format!("{base}.with_qualities({qualities})"),
        None => base,
    }
}

fn qualities_expr(attribute: &Attribute) -> String {
    let quality = &attribute.quality;
    let mut parts = Vec::new();
    if quality.nullable {
        parts.push("AttributeQualities::NULLABLE");
    }
    if quality.persistence.as_deref() == Some("nonVolatile") {
        parts.push("AttributeQualities::NON_VOLATILE");
    }
    if quality.persistence.as_deref() == Some("fixed") {
        parts.push("AttributeQualities::FIXED");
    }
    if quality.atomic {
        parts.push("AttributeQualities::ATOMIC");
    }
    if quality.large {
        parts.push("AttributeQualities::LARGE");
    }
    if quality.scene {
        parts.push("AttributeQualities::SCENE");
    }
    if parts.is_empty() {
        "AttributeQualities::empty()".to_owned()
    } else {
        parts.join(".union(") + &")".repeat(parts.len() - 1)
    }
}

fn reporting_expr(attribute: &Attribute) -> String {
    if attribute.quality.changes_omitted {
        "Reporting::ChangesOmitted".to_owned()
    } else if attribute.quality.quieter {
        "Reporting::Quieter".to_owned()
    } else {
        "Reporting::OnChange".to_owned()
    }
}

// --- Conformance ------------------------------------------------------------------------------

fn conform_expr(cluster: &Cluster, conform: &Conform) -> String {
    if conform.clauses.len() == 1 {
        let clause = &conform.clauses[0];
        if clause.when == Condition::Always {
            return match clause.verdict {
                Verdict::Mandatory => "Conform::MANDATORY".to_owned(),
                Verdict::Optional => "Conform::OPTIONAL".to_owned(),
                Verdict::Disallowed => "Conform::DISALLOWED".to_owned(),
                Verdict::Described => "Conform::DESCRIBED".to_owned(),
                other => format!(
                    "Conform {{ clauses: &[Clause::always({})] }}",
                    verdict_expr(other)
                ),
            };
        }
    }
    let clauses = conform
        .clauses
        .iter()
        .map(|clause| {
            format!(
                "Clause {{ verdict: {}, when: {} }}",
                verdict_expr(clause.verdict),
                condition_expr(cluster, &clause.when)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("Conform {{ clauses: &[{clauses}] }}")
}

fn verdict_expr(verdict: Verdict) -> &'static str {
    match verdict {
        Verdict::Mandatory => "Conformance::Mandatory",
        Verdict::Optional => "Conformance::Optional",
        Verdict::Provisional => "Conformance::Provisional",
        Verdict::Deprecated => "Conformance::Deprecated",
        Verdict::Disallowed => "Conformance::Disallowed",
        Verdict::Described => "Conformance::Described",
    }
}

fn condition_expr(cluster: &Cluster, condition: &Condition) -> String {
    match condition {
        Condition::Always => "Condition::Always".to_owned(),
        Condition::Feature(code) => match cluster
            .features
            .iter()
            .find(|f| f.code == *code || f.name == *code)
        {
            Some(feature) => format!("Condition::Feature({})", feature.bit),
            // A feature this cluster does not define — a derived cluster naming its base's, or
            // a scraper slip. Recorded by name so the validator reports it as prose rather
            // than resolving it to a bit that means something else.
            None => format!("Condition::Named({code:?})"),
        },
        Condition::Attribute(name) => match cluster.attributes.iter().find(|a| a.name == *name) {
            Some(attribute) => format!("Condition::Attribute({:#06X})", attribute.id),
            None => format!("Condition::Named({name:?})"),
        },
        Condition::Command(name) => match cluster.commands.iter().find(|c| c.name == *name) {
            Some(command) => format!("Condition::Command({:#04X})", command.id),
            None => format!("Condition::Named({name:?})"),
        },
        Condition::Event(name) => match cluster.events.iter().find(|e| e.name == *name) {
            Some(event) => format!("Condition::Event({:#04X})", event.id),
            None => format!("Condition::Named({name:?})"),
        },
        Condition::Cluster(name) => format!("Condition::Named({name:?})"),
        // A sibling field. The runtime's `Supports` answers about a *cluster's* elements and
        // has no view inside one structure, so this is recorded by name and evaluates to
        // `Described` — the specification's own words decide, which for "unicast or groupcast,
        // never both" is what a reader needs anyway.
        Condition::Field(name) => format!("Condition::Named({:?})", format!("field:{name}")),
        Condition::Named(name) => format!("Condition::Named({name:?})"),
        Condition::Not(inner) => format!("Condition::Not(&{})", condition_expr(cluster, inner)),
        Condition::All(terms) => format!("Condition::All(&[{}])", term_list(cluster, terms)),
        Condition::Any(terms) => format!("Condition::Any(&[{}])", term_list(cluster, terms)),
        Condition::ExactlyOne(terms) => {
            format!("Condition::ExactlyOne(&[{}])", term_list(cluster, terms))
        }
        // Unreachable: a clause holding one became `Described` in the parser.
        Condition::Comparison => "Condition::Named(\"comparison\")".to_owned(),
    }
}

fn term_list(cluster: &Cluster, terms: &[Condition]) -> String {
    terms
        .iter()
        .map(|term| condition_expr(cluster, term))
        .collect::<Vec<_>>()
        .join(", ")
}

// --- Device types ------------------------------------------------------------------------------

fn device_types_file(model: &DataModel, names: &[String]) -> String {
    let mut out = header(
        &model.version,
        "Every device type the Device Library defines.",
    );
    out.push_str(
        "//! The Matter device types (Device Library), generated from the CSA data model.\n\
         //!\n\
         //! A device type says which clusters an endpoint must and may serve, and sometimes\n\
         //! narrows a cluster further — On/Off Light requires On/Off *with* its Lighting\n\
         //! feature. `Descriptor`'s `DeviceTypeList` is what advertises one; this is what\n\
         //! says whether the endpoint behind it is furnished correctly.\n\n\
         #![allow(unused_imports)]\n\n\
         use crate::dm::conformance::{Clause, Condition, Conform, Conformance};\n\
         use crate::dm::device::{DeviceType, RequiredCluster};\n\
         use crate::im::ClusterId;\n\n",
    );

    let mut all = String::new();
    for (name, device) in names.iter().zip(&model.device_types) {
        let constant = ident::screaming(&device.name);
        let _ = writeln!(
            out,
            "/// {} — device type `{:#06X}`, revision {}.\n\
             pub const {constant}: DeviceType = DeviceType {{\n\
             \x20   id: {:#06X},\n\
             \x20   name: {:?},\n\
             \x20   revision: {},\n\
             \x20   class: {:?},\n\
             \x20   scope: {:?},\n\
             \x20   clusters: &[",
            ident::doc(&device.name),
            device.id,
            device.revision,
            device.id,
            device.name,
            device.revision,
            device.class,
            device.scope
        );
        for cluster in &device.clusters {
            let _ = writeln!(
                out,
                "        RequiredCluster {{ id: {:#06X}, name: {:?}, server: {}, conform: {}, features: {}, attributes: {}, commands: {}, events: {} }},",
                cluster.id,
                cluster.name,
                cluster.side != "client",
                device_conform_expr(&cluster.conform),
                requirement_list(&cluster.features),
                requirement_list(&cluster.attributes),
                requirement_list(&cluster.commands),
                requirement_list(&cluster.events),
            );
        }
        out.push_str("    ],\n};\n\n");
        let _ = writeln!(all, "    &{constant},");
        let _ = name;
    }

    let _ = writeln!(
        out,
        "/// Every device type, sorted by id.\n\
         pub const ALL: &[&DeviceType] = &[\n{all}];\n"
    );
    out.push_str(
        "/// The device type with this id, if the library defines one.\n\
         #[must_use]\n\
         pub fn find(id: u32) -> Option<&'static DeviceType> {\n\
         \x20   ALL.iter().copied().find(|device| device.id == id)\n\
         }\n",
    );
    out
}

/// A device type's conformance never refers to features by code, so there is no cluster to
/// resolve against.
fn device_conform_expr(conform: &Conform) -> String {
    let empty = Cluster {
        id: 0,
        name: String::new(),
        revision: 0,
        pics: String::new(),
        base_cluster: None,
        is_base: true,
        features: Vec::new(),
        enums: Vec::new(),
        bitmaps: Vec::new(),
        structs: Vec::new(),
        typedefs: Vec::new(),
        attributes: Vec::new(),
        commands: Vec::new(),
        events: Vec::new(),
    };
    conform_expr(&empty, conform)
}

/// A device type's extra requirements on one cluster, as `(name, conformance)` pairs.
fn requirement_list(items: &[(String, Conform)]) -> String {
    if items.is_empty() {
        return "&[]".to_owned();
    }
    let entries = items
        .iter()
        .map(|(name, conform)| format!("({name:?}, {})", device_conform_expr(conform)))
        .collect::<Vec<_>>()
        .join(", ");
    format!("&[{entries}]")
}

// --- Structures and command payloads ------------------------------------------------------

/// One field, resolved and named.
struct Member {
    /// The Rust field name.
    name: String,
    /// The specification's name, for the doc line.
    spec_name: String,
    /// Its context tag.
    tag: u8,
    /// The Rust type, already wrapped in `Option`/`Nullable` as its qualities require.
    rust: String,
    /// Whether the field may be absent.
    optional: bool,
    /// Whether it borrows.
    borrows: bool,
    /// The resolved base, for the decode arm.
    resolved: Resolved,
    nullable: bool,
}

/// Resolves a field list, or `None` if any field's type could not be mapped.
///
/// All or nothing on purpose. A structure with one field quietly missing is worse than no
/// structure at all: it decodes, it round-trips, and it silently drops whatever the field
/// carried — and the caller has no way to find out.
fn members(fields: &[Field], cluster: &Cluster, types: &Types) -> Option<Vec<Member>> {
    let mut names: Vec<String> = fields.iter().map(|f| ident::snake(&f.name)).collect();
    ident::unique(&mut names);
    let mut out = Vec::new();
    for (name, field) in names.into_iter().zip(fields) {
        let resolved = types.resolve(&field.kind, field.entry.as_deref(), cluster);
        if !resolved.is_known() {
            return None;
        }
        // §7.3's `O` on a field means it may be absent; §7.12's `X` means it may be null.
        // Both at once is three states, and `Option<Nullable<T>>` keeps all three.
        let optional =
            !field.conform.clauses.iter().any(|clause| {
                clause.verdict == Verdict::Mandatory && clause.when == Condition::Always
            });
        let mut rust = resolved.rust();
        if field.nullable {
            rust = format!("Nullable<{rust}>");
        }
        if optional {
            rust = format!("Option<{rust}>");
        }
        out.push(Member {
            name,
            spec_name: field.name.clone(),
            tag: field.id,
            rust,
            optional,
            borrows: resolved.borrows(),
            resolved,
            nullable: field.nullable,
        });
    }
    Some(out)
}

/// Writes a `struct` with its `ToTlv` and `FromTlv`.
fn emit_struct(out: &mut String, name: &str, doc: &str, members: &[Member], borrows: bool) {
    let lifetime = if borrows { "<'a>" } else { "" };
    let _ = writeln!(out, "/// {doc}");
    let _ = writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq)]\npub struct {name}{lifetime} {{"
    );
    for member in members {
        let _ = writeln!(
            out,
            "    /// `{}`, field {}.\n    pub {}: {},",
            member.spec_name, member.tag, member.name, member.rust
        );
    }
    if members.is_empty() {
        // A command with no fields still needs a type, so that `invoke` has something to
        // decode into and the generated code has one shape rather than two.
        let _ = writeln!(
            out,
            "    /// This structure has no fields.\n    pub _empty: (),"
        );
    }
    out.push_str("}\n\n");

    // --- ToTlv ---
    let _ = writeln!(
        out,
        "impl{lifetime} ToTlv for {name}{lifetime} {{\n\
         \x20   fn to_tlv(&self, w: &mut TlvWriter<'_>, tag: Tag) -> Result<()> {{\n\
         \x20       w.start_structure(tag)?;"
    );
    for member in members {
        if member.optional {
            let _ = writeln!(
                out,
                "        if let Some(value) = &self.{} {{\n\
                 \x20           value.to_tlv(w, Tag::Context({}))?;\n\
                 \x20       }}",
                member.name, member.tag
            );
        } else {
            let _ = writeln!(
                out,
                "        self.{}.to_tlv(w, Tag::Context({}))?;",
                member.name, member.tag
            );
        }
    }
    out.push_str("        w.end_container()\n    }\n}\n\n");

    // --- FromTlv ---
    let read_lifetime = if borrows { "'a" } else { "'_" };
    let _ = writeln!(
        out,
        "impl<'a> FromTlv<'a> for {name}{lifetime} {{\n\
         \x20   fn from_tlv(reader: &mut TlvReader<'a>, element: &Element<'a>) -> Result<Self> {{\n\
         \x20       if element.value.container() != Some(ContainerKind::Structure) {{\n\
         \x20           return Err(crate::Error::new(crate::ErrorCode::TlvWrongType));\n\
         \x20       }}"
    );
    let _ = read_lifetime;
    for member in members {
        let _ = writeln!(out, "        let mut {} = None;", member.name);
    }
    out.push_str(
        "        loop {\n\
         \x20           let Some(field) = reader.next_element()? else {\n\
         \x20               return Err(crate::Error::new(crate::ErrorCode::TlvTruncated));\n\
         \x20           };\n\
         \x20           if field.value == Value::EndOfContainer {\n\
         \x20               break;\n\
         \x20           }\n\
         \x20           match field.tag.context() {\n",
    );
    for member in members {
        let ty = if member.nullable {
            format!("Nullable<{}>", member.resolved.rust())
        } else {
            member.resolved.rust()
        };
        let _ = writeln!(
            out,
            "                Some({}) => {} = Some(<{ty}>::from_tlv(reader, &field)?),",
            member.tag, member.name
        );
    }
    out.push_str(
        "                // A field this revision does not define. §7.19.2: a receiver\n\
         \x20               // ignores what it does not know rather than refusing the whole\n\
         \x20               // structure, which is what lets a newer peer talk to an older one.\n\
         \x20               _ => reader.skip_value(&field)?,\n\
         \x20           }\n\
         \x20       }\n",
    );
    out.push_str("        Ok(Self {\n");
    for member in members {
        if member.optional {
            let _ = writeln!(out, "            {},", member.name);
        } else {
            let _ = writeln!(
                out,
                "            {}: {}.ok_or(crate::Error::new(crate::ErrorCode::TlvNotFound))?,",
                member.name, member.name
            );
        }
    }
    if members.is_empty() {
        out.push_str("            _empty: (),\n");
    }
    out.push_str("        })\n    }\n}\n\n");
}

fn emit_structs(out: &mut String, cluster: &Cluster, types: &Types) {
    for structure in &cluster.structs {
        emit_one_struct(out, structure, cluster, types);
    }
}

fn emit_one_struct(out: &mut String, structure: &Structure, cluster: &Cluster, types: &Types) {
    let Some(mut members) = members(&structure.fields, cluster, types) else {
        let _ = writeln!(
            out,
            "// `{}` is not generated: one of its fields has a type with no Rust mapping.\n",
            structure.name
        );
        return;
    };
    if structure.fabric_scoped {
        // §7.19.1.9's global field. The XML never lists it — every fabric-scoped structure has
        // it, so saying so would be noise — and a generated type without it produces entries
        // that belong to no fabric, which is the whole basis of §6.6's isolation.
        members.push(Member {
            name: "fabric_index".to_owned(),
            spec_name: "FabricIndex".to_owned(),
            tag: 254,
            rust: "crate::msg::FabricIndex".to_owned(),
            optional: false,
            borrows: false,
            resolved: Resolved::Scalar("crate::msg::FabricIndex".to_owned()),
            nullable: false,
        });
    }
    let name = ident::pascal(&structure.name);
    let borrows = types.struct_borrows(cluster, &structure.name);
    let doc = if structure.fabric_scoped {
        format!(
            "`{}`, fabric-scoped — §7.19.1.9's `FabricIndex` is field 254.",
            structure.name
        )
    } else {
        format!("`{}`.", structure.name)
    };
    emit_struct(out, &name, &doc, &members, borrows);
}

/// Writes a payload type for every command that takes fields.
fn emit_payloads(out: &mut String, cluster: &Cluster, types: &Types) {
    let mut names: Vec<String> = cluster
        .commands
        .iter()
        .map(|command| format!("{}Fields", ident::pascal(&command.name)))
        .collect();
    ident::unique(&mut names);
    for (name, command) in names.iter().zip(&cluster.commands) {
        if command.fields.is_empty() {
            continue;
        }
        let Some(members) = members(&command.fields, cluster, types) else {
            let _ = writeln!(
                out,
                "// `{}`'s fields are not generated: one has a type with no Rust mapping.\n",
                command.name
            );
            continue;
        };
        let borrows = members.iter().any(|m| m.borrows);
        let doc = format!(
            "The fields of `{}` (command `{:#04X}`).",
            command.name, command.id
        );
        emit_struct(out, name, &doc, &members, borrows);
    }
}
